-- EMS ingestion relations. Wire counters are arbitrary precision integers.
CREATE DOMAIN ems_counter AS numeric CHECK(VALUE >= 0 AND VALUE=trunc(VALUE) AND VALUE NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric));
CREATE DOMAIN ems_positive_counter AS numeric CHECK(VALUE > 0 AND VALUE=trunc(VALUE) AND VALUE NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric));
CREATE DOMAIN ems_uuid_v4 AS uuid CHECK(VALUE::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$');
CREATE DOMAIN ems_content_hash AS text CHECK(VALUE ~ '^[0-9a-f]{64}$');
CREATE TABLE ems_gateway (
    ems_uuid ems_uuid_v4 PRIMARY KEY,
    device_id bigint NOT NULL UNIQUE REFERENCES device(id)
);
-- Station is retained here as an historical authorization fact, rather than inferred from today's asset.
CREATE TABLE ems_binding_period (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    station_id bigint NOT NULL REFERENCES station,
    UNIQUE(id,ems_uuid),
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    CHECK(valid_to IS NULL OR valid_to>valid_from),
    EXCLUDE USING gist(ems_uuid WITH =,tstzrange(valid_from,valid_to,'[)') WITH &&)
);
CREATE TABLE connection_state (
    ems_uuid ems_uuid_v4 PRIMARY KEY REFERENCES ems_gateway,
    connection_id ems_uuid_v4,
    ingress_generation uuid,
    ingress_order ems_counter,
    last_fresh_heartbeat timestamptz,
    lease_owner text,
    lease_until timestamptz,
    fencing_token ems_counter NOT NULL DEFAULT 0,
    CHECK((lease_owner IS NULL)=(lease_until IS NULL)),
    CHECK(lease_owner IS NULL OR btrim(lease_owner)<>''),
    CHECK((connection_id IS NULL)=(ingress_generation IS NULL)),
    CHECK(connection_id IS NOT NULL OR last_fresh_heartbeat IS NULL)
);
CREATE TABLE retired_connection (
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    ingress_generation uuid NOT NULL,
    connection_id ems_uuid_v4 NOT NULL,
    retired_at timestamptz NOT NULL,
    PRIMARY KEY(ems_uuid,ingress_generation,connection_id)
);
-- Globally immutable version content; authorization is a separate acceptance fact.
CREATE TABLE structure_revision (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    sv ems_positive_counter NOT NULL,
    layout jsonb NOT NULL CHECK(jsonb_typeof(layout)='object'),
    content_hash ems_content_hash NOT NULL,
    UNIQUE(ems_uuid,sv)
);
CREATE TABLE structure_acceptance (
    binding_period_id bigint NOT NULL REFERENCES ems_binding_period,
    revision_id bigint NOT NULL REFERENCES structure_revision,
    received_at timestamptz NOT NULL,
    PRIMARY KEY(binding_period_id,revision_id)
);
CREATE TABLE structure_current (
    ems_uuid ems_uuid_v4 PRIMARY KEY REFERENCES ems_gateway,
    binding_period_id bigint NOT NULL,
    connection_id ems_uuid_v4 NOT NULL,
    seq ems_positive_counter NOT NULL,
    revision_id bigint REFERENCES structure_revision,
    metadata jsonb NOT NULL CHECK(jsonb_typeof(metadata)='object'),
    received_at timestamptz NOT NULL,
    FOREIGN KEY(binding_period_id,ems_uuid) REFERENCES ems_binding_period(id,ems_uuid),
    FOREIGN KEY(binding_period_id,revision_id) REFERENCES structure_acceptance
);
CREATE TABLE device_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_period_id bigint NOT NULL REFERENCES ems_binding_period,
    scope text NOT NULL CHECK(scope IN ('ems','cabinet','public')),
    cabinet_no smallint,
    role text NOT NULL CHECK(role IN ('ems','emu','bms','bmu','pcs','dcdc','tms','meter')),
    CHECK((scope='ems' AND role='ems') OR (scope='public' AND role='meter') OR (scope='cabinet' AND role<>'ems')),
    local_no ems_positive_counter NOT NULL,
    device_id bigint NOT NULL REFERENCES device,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    CHECK((scope='cabinet' AND cabinet_no IS NOT NULL AND cabinet_no BETWEEN 1 AND 30) OR (scope<>'cabinet' AND cabinet_no IS NULL)),
    CHECK(valid_to IS NULL OR valid_to>valid_from),
    EXCLUDE USING gist(binding_period_id WITH =,scope WITH =,(coalesce(cabinet_no,0)) WITH =,role WITH =,local_no WITH =,tstzrange(valid_from,valid_to,'[)') WITH &&)
);
CREATE TABLE bmu_layout (
    ems_uuid ems_uuid_v4 NOT NULL,
    sv ems_positive_counter NOT NULL,
    cabinet_no smallint NOT NULL CHECK(cabinet_no BETWEEN 1 AND 30),
    slot smallint NOT NULL CHECK(slot BETWEEN 1 AND 10),
    voltage_count smallint CHECK(voltage_count BETWEEN 1 AND 255),
    temperature_count smallint CHECK(temperature_count BETWEEN 1 AND 255),
    PRIMARY KEY(ems_uuid,sv,cabinet_no,slot),
    FOREIGN KEY(ems_uuid,sv) REFERENCES structure_revision(ems_uuid,sv)
);
CREATE TABLE point_definition (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_version text NOT NULL CHECK(btrim(catalog_version)<>''),
    namespace text NOT NULL CHECK(namespace IN ('ems','cabinet','config')),
    source_id ems_positive_counter NOT NULL,
    kind_code varchar(60) REFERENCES measurement_kind,
    value_type text NOT NULL CHECK(value_type IN ('number','text','boolean','u16_words','scalar','unknown')),
    aggregation text CHECK(aggregation IN ('none','sum','average','min','max','last','delta')),
    UNIQUE(catalog_version,namespace,source_id),
    UNIQUE(id,value_type)
);
CREATE TABLE point_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_binding_id bigint NOT NULL REFERENCES device_binding,
    definition_id bigint NOT NULL REFERENCES point_definition,
    measurement_point_id bigint NOT NULL REFERENCES measurement_point,
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    CHECK(valid_to IS NULL OR valid_to>valid_from),
    EXCLUDE USING gist(device_binding_id WITH =,definition_id WITH =,tstzrange(valid_from,valid_to,'[)') WITH &&)
);
CREATE TABLE config_revision (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    cfg_rev ems_counter NOT NULL,
    content_hash ems_content_hash NOT NULL,
    UNIQUE(ems_uuid,cfg_rev)
);
CREATE TABLE config_acceptance (
    binding_period_id bigint NOT NULL REFERENCES ems_binding_period,
    revision_id bigint NOT NULL REFERENCES config_revision,
    received_at timestamptz NOT NULL,
    PRIMARY KEY(binding_period_id,revision_id)
);
CREATE TABLE config_current (
    ems_uuid ems_uuid_v4 PRIMARY KEY REFERENCES ems_gateway,
    binding_period_id bigint NOT NULL,
    revision_id bigint NOT NULL,
    FOREIGN KEY(binding_period_id,ems_uuid) REFERENCES ems_binding_period(id,ems_uuid),
    FOREIGN KEY(binding_period_id,revision_id) REFERENCES config_acceptance
);
-- null is a reserved configuration value. Scalar preserves the protocol's unresolved number/text metadata.
CREATE TABLE config_value (
    revision_id bigint NOT NULL REFERENCES config_revision,
    definition_id bigint NOT NULL,
    value_type text NOT NULL,
    number_value numeric CHECK(number_value NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric)),
    text_value text,
    boolean_value boolean,
    words_value jsonb,
    PRIMARY KEY(revision_id,definition_id),
    FOREIGN KEY(definition_id,value_type) REFERENCES point_definition(id,value_type),
    CHECK(num_nonnulls(number_value,text_value,boolean_value,words_value)<=1),
    CHECK((value_type='number' AND num_nonnulls(text_value,boolean_value,words_value)=0) OR (value_type='text' AND num_nonnulls(number_value,boolean_value,words_value)=0) OR (value_type='boolean' AND num_nonnulls(number_value,text_value,words_value)=0) OR (value_type='scalar' AND words_value IS NULL) OR (value_type='u16_words' AND num_nonnulls(number_value,text_value,boolean_value)=0))
);
CREATE TABLE reliable_message (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    binding_period_id bigint NOT NULL,
    type text NOT NULL CHECK(type IN ('alarm_event','alarm_data','important_history')),
    alarm_id ems_uuid_v4,
    seq ems_positive_counter,
    task_id ems_uuid_v4,
    part ems_positive_counter,
    parts ems_positive_counter,
    source_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL,
    raw_payload bytea NOT NULL,
    content_hash ems_content_hash NOT NULL,
    status text NOT NULL CHECK(status IN ('saved','projected','projection_failed')),
    CHECK((type='alarm_event' AND alarm_id IS NOT NULL AND seq IS NOT NULL AND task_id IS NULL AND part IS NULL AND parts IS NULL) OR (type='alarm_data' AND alarm_id IS NOT NULL AND seq IS NULL AND task_id IS NULL AND part IS NULL AND parts IS NULL) OR (type='important_history' AND alarm_id IS NULL AND seq IS NULL AND task_id IS NOT NULL AND part IS NOT NULL AND parts IS NOT NULL AND part<=parts)),
    UNIQUE(id,ems_uuid),
    FOREIGN KEY(binding_period_id,ems_uuid) REFERENCES ems_binding_period(id,ems_uuid)
);
CREATE UNIQUE INDEX reliable_event_key ON reliable_message(ems_uuid,alarm_id,seq) WHERE type='alarm_event';
CREATE UNIQUE INDEX reliable_alarm_data_key ON reliable_message(ems_uuid,alarm_id) WHERE type='alarm_data';
CREATE UNIQUE INDEX reliable_history_key ON reliable_message(ems_uuid,task_id,part) WHERE type='important_history';
CREATE TABLE history_sample_identity (
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    cabinet_no smallint NOT NULL CHECK(cabinet_no BETWEEN 1 AND 30),
    source_id ems_positive_counter NOT NULL,
    archived_at timestamptz NOT NULL,
    canonical_value jsonb NOT NULL,
    reliable_message_id bigint NOT NULL,
    PRIMARY KEY(ems_uuid,cabinet_no,source_id,archived_at),
    FOREIGN KEY(reliable_message_id,ems_uuid) REFERENCES reliable_message(id,ems_uuid),
    CHECK(jsonb_typeof(canonical_value) IN ('number','string','boolean','null'))
);
CREATE TABLE ems_alarm_identity (
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    alarm_id ems_uuid_v4 NOT NULL,
    business_alarm_id bigint UNIQUE REFERENCES alarm,
    PRIMARY KEY(ems_uuid,alarm_id)
);
CREATE TABLE ems_alarm_event (
    ems_uuid ems_uuid_v4 NOT NULL,
    alarm_id ems_uuid_v4 NOT NULL,
    seq ems_positive_counter NOT NULL,
    reliable_message_id bigint NOT NULL UNIQUE,
    PRIMARY KEY(ems_uuid,alarm_id,seq),
    FOREIGN KEY(ems_uuid,alarm_id) REFERENCES ems_alarm_identity,
    FOREIGN KEY(reliable_message_id,ems_uuid) REFERENCES reliable_message(id,ems_uuid)
);
CREATE TABLE alarm_current_snapshot (
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    cabinet_no smallint NOT NULL CHECK(cabinet_no BETWEEN 1 AND 30),
    connection_id ems_uuid_v4 NOT NULL,
    seq ems_positive_counter NOT NULL,
    known boolean NOT NULL,
    observed_at timestamptz NOT NULL,
    refresh_required boolean NOT NULL DEFAULT false,
    PRIMARY KEY(ems_uuid,cabinet_no),
    UNIQUE(ems_uuid,cabinet_no,connection_id,seq)
);
CREATE TABLE alarm_current_member (
    ems_uuid ems_uuid_v4 NOT NULL,
    cabinet_no smallint NOT NULL,
    connection_id ems_uuid_v4 NOT NULL,
    seq ems_positive_counter NOT NULL,
    alarm_id ems_uuid_v4 NOT NULL,
    PRIMARY KEY(ems_uuid,cabinet_no,alarm_id),
    FOREIGN KEY(ems_uuid,cabinet_no,connection_id,seq) REFERENCES alarm_current_snapshot(ems_uuid,cabinet_no,connection_id,seq) ON DELETE CASCADE,
    FOREIGN KEY(ems_uuid,alarm_id) REFERENCES ems_alarm_identity
);
CREATE TABLE query_request (
    id uuid PRIMARY KEY,
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    -- NULL is an automatic read-only service query, never a fabricated user.
    actor_id bigint REFERENCES app_user,
    binding_period_id bigint NOT NULL REFERENCES ems_binding_period,
    connection_id ems_uuid_v4 NOT NULL,
    operation text NOT NULL CHECK(operation IN ('structure.get','alarm.current.get','communication.status.get')),
    params jsonb NOT NULL CHECK(jsonb_typeof(params)='object'),
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    status text NOT NULL CHECK(status IN ('pending','sent','succeeded','failed','expired','unknown')),
    result jsonb,
    CHECK(expires_at>created_at),
    CHECK(status<>'succeeded' OR result IS NOT NULL),
    UNIQUE(id,ems_uuid),
    FOREIGN KEY(binding_period_id,ems_uuid) REFERENCES ems_binding_period(id,ems_uuid)
);
CREATE TABLE outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ems_uuid ems_uuid_v4 NOT NULL REFERENCES ems_gateway,
    type text NOT NULL CHECK(type IN ('query','saved_ack')),
    query_request_id uuid,
    reliable_message_id bigint,
    topic text NOT NULL CHECK(btrim(topic)<>''),
    payload bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sending','sent','failed','cancelled')),
    attempts integer NOT NULL DEFAULT 0 CHECK(attempts>=0),
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    lease_owner text,
    lease_until timestamptz,
    fencing_token ems_counter NOT NULL DEFAULT 0,
    CHECK((lease_owner IS NULL)=(lease_until IS NULL)),
    CHECK((type='query' AND query_request_id IS NOT NULL AND reliable_message_id IS NULL) OR (type='saved_ack' AND query_request_id IS NULL AND reliable_message_id IS NOT NULL)),
    FOREIGN KEY(query_request_id,ems_uuid) REFERENCES query_request(id,ems_uuid),
    FOREIGN KEY(reliable_message_id,ems_uuid) REFERENCES reliable_message(id,ems_uuid),
    UNIQUE(query_request_id),
    UNIQUE(reliable_message_id)
);
CREATE INDEX outbox_pending ON outbox(next_attempt_at,id) WHERE status IN ('pending','sending');
CREATE INDEX query_rate_window ON query_request(ems_uuid,connection_id,created_at);

-- Lock the asset row when validating current station ownership, so a concurrent move cannot bypass validation.
CREATE FUNCTION check_ems_binding_period() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    asset_station bigint;
BEGIN
    IF TG_OP='UPDATE' AND (NEW.ems_uuid,NEW.station_id,NEW.valid_from) IS DISTINCT FROM (OLD.ems_uuid,OLD.station_id,OLD.valid_from) THEN
        RAISE EXCEPTION 'Binding historical identity is immutable' USING ERRCODE='23514';
    END IF;
    SELECT d.station_id INTO asset_station FROM device d JOIN ems_gateway g ON g.device_id=d.id WHERE g.ems_uuid=NEW.ems_uuid FOR UPDATE OF d;
    IF (TG_OP='INSERT' OR NEW.valid_to IS NULL) AND NEW.station_id IS DISTINCT FROM asset_station THEN
        RAISE EXCEPTION 'EMS station mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_period_station BEFORE INSERT OR UPDATE ON ems_binding_period FOR EACH ROW EXECUTE FUNCTION check_ems_binding_period();
CREATE FUNCTION check_ems_device_binding() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    period ems_binding_period;
    asset_station bigint;
BEGIN
    SELECT * INTO period FROM ems_binding_period WHERE id=NEW.binding_period_id FOR SHARE;
    SELECT station_id INTO asset_station FROM device WHERE id=NEW.device_id FOR UPDATE;
    IF period.id IS NULL OR asset_station IS DISTINCT FROM period.station_id OR NOT (tstzrange(NEW.valid_from,NEW.valid_to,'[)') <@ tstzrange(period.valid_from,period.valid_to,'[)')) THEN
        RAISE EXCEPTION 'Device binding station or period mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_device_binding_guard BEFORE INSERT OR UPDATE ON device_binding FOR EACH ROW EXECUTE FUNCTION check_ems_device_binding();
CREATE FUNCTION check_ems_asset_move() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.station_id IS DISTINCT FROM OLD.station_id AND
    (EXISTS(SELECT 1 FROM ems_binding_period p JOIN ems_gateway g USING(ems_uuid) WHERE g.device_id=OLD.id AND p.valid_to IS NULL) OR
    EXISTS(SELECT 1 FROM device_binding WHERE device_id=OLD.id AND valid_to IS NULL)) THEN
        RAISE EXCEPTION 'Close active EMS bindings before moving asset' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_asset_move BEFORE UPDATE OF station_id ON device FOR EACH ROW EXECUTE FUNCTION check_ems_asset_move();
CREATE FUNCTION check_ems_point_binding() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    binding device_binding;
    point_device bigint;
    definition_namespace text;
    definition_type text;
    definition_source numeric;
BEGIN
    SELECT * INTO binding FROM device_binding WHERE id=NEW.device_binding_id FOR UPDATE;
    SELECT device_id INTO point_device FROM measurement_point WHERE id=NEW.measurement_point_id FOR SHARE;
    SELECT namespace,value_type,source_id INTO definition_namespace,definition_type,definition_source FROM point_definition WHERE id=NEW.definition_id;
    IF EXISTS (
    SELECT 1 FROM point_binding pb JOIN point_definition pd ON pd.id=pb.definition_id
    WHERE pb.device_binding_id=NEW.device_binding_id AND pb.id IS DISTINCT FROM NEW.id
    AND pd.namespace=definition_namespace AND pd.source_id=definition_source
    AND tstzrange(pb.valid_from,pb.valid_to,'[)') && tstzrange(NEW.valid_from,NEW.valid_to,'[)')
    ) THEN
        RAISE EXCEPTION 'Source position already mapped in another catalog version' USING ERRCODE='23514';
    END IF;
    IF binding.id IS NULL OR binding.device_id IS DISTINCT FROM point_device OR definition_type='unknown' OR
    definition_namespace='config' OR (definition_namespace='cabinet' AND binding.scope<>'cabinet') OR
    (definition_namespace='ems' AND binding.scope<>'ems') OR
    NOT(tstzrange(NEW.valid_from,NEW.valid_to,'[)') <@ tstzrange(binding.valid_from,binding.valid_to,'[)')) THEN
        RAISE EXCEPTION 'Point binding asset, namespace or period mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_point_binding_guard BEFORE INSERT OR UPDATE ON point_binding FOR EACH ROW EXECUTE FUNCTION check_ems_point_binding();
INSERT INTO permission(code,name) VALUES('ems.read','查看 EMS 接入'),('ems.manage','管理 EMS 绑定'),('ems.query','查询 EMS 状态');
INSERT INTO role_permission(role_id,permission_code)
 SELECT r.id,p.code FROM app_role r CROSS JOIN permission p
 WHERE r.code='bootstrap_super_admin__o2' AND p.code IN ('ems.read','ems.manage','ems.query') ON CONFLICT DO NOTHING;

CREATE FUNCTION ems_valid_u16_words(value jsonb) RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE WHEN value IS NULL THEN true WHEN jsonb_typeof(value)<>'array' THEN false
 WHEN jsonb_array_length(value)<>4 THEN false ELSE NOT EXISTS(
 SELECT 1 FROM jsonb_array_elements(value) v WHERE CASE WHEN jsonb_typeof(v)<>'number' THEN true
 ELSE (v::text)::numeric<>trunc((v::text)::numeric) OR (v::text)::numeric NOT BETWEEN 0 AND 65535 END) END
$$;
ALTER TABLE config_value ADD CHECK(ems_valid_u16_words(words_value));
CREATE FUNCTION check_ems_config_value() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM point_definition WHERE id=NEW.definition_id AND namespace='config') THEN
        RAISE EXCEPTION 'Configuration requires config namespace' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_config_namespace BEFORE INSERT OR UPDATE ON config_value FOR EACH ROW EXECUTE FUNCTION check_ems_config_value();
CREATE FUNCTION check_ems_query_binding() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM ems_binding_period WHERE id=NEW.binding_period_id AND ems_uuid=NEW.ems_uuid AND
    NEW.created_at>=valid_from AND (valid_to IS NULL OR NEW.created_at<valid_to)) THEN
        RAISE EXCEPTION 'Query historical authorization mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_query_binding BEFORE INSERT OR UPDATE ON query_request FOR EACH ROW EXECUTE FUNCTION check_ems_query_binding();
CREATE FUNCTION check_ems_known_alarm_member() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM alarm_current_snapshot WHERE ems_uuid=NEW.ems_uuid AND cabinet_no=NEW.cabinet_no AND known) THEN
        RAISE EXCEPTION 'Unknown alarm snapshot has no known members' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_known_alarm_member BEFORE INSERT OR UPDATE ON alarm_current_member FOR EACH ROW EXECUTE FUNCTION check_ems_known_alarm_member();
CREATE FUNCTION check_ems_parent_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_TABLE_NAME='ems_gateway' THEN
        IF NEW.device_id<>OLD.device_id THEN
            RAISE EXCEPTION 'EMS asset identity is immutable' USING ERRCODE='23514';
        END IF;
    ELSIF TG_TABLE_NAME='measurement_point' THEN
        IF NEW.device_id<>OLD.device_id AND EXISTS(SELECT 1 FROM point_binding WHERE measurement_point_id=OLD.id) THEN
            RAISE EXCEPTION 'Mapped measurement asset identity is immutable' USING ERRCODE='23514';
        END IF;
    ELSIF TG_TABLE_NAME='ems_binding_period' THEN
        PERFORM pg_advisory_xact_lock(hashtextextended(NEW.ems_uuid::text,78291029));
        IF EXISTS(SELECT 1 FROM structure_acceptance WHERE binding_period_id=NEW.id AND
           (received_at<NEW.valid_from OR (NEW.valid_to IS NOT NULL AND received_at>=NEW.valid_to))) OR
           EXISTS(SELECT 1 FROM config_acceptance WHERE binding_period_id=NEW.id AND
           (received_at<NEW.valid_from OR (NEW.valid_to IS NOT NULL AND received_at>=NEW.valid_to))) THEN
            RAISE EXCEPTION 'Period change would invalidate accepted version receipt' USING ERRCODE='23514';
        END IF;
        IF EXISTS(SELECT 1 FROM device_binding WHERE binding_period_id=NEW.id AND NOT(tstzrange(valid_from,valid_to,'[)') <@ tstzrange(NEW.valid_from,NEW.valid_to,'[)'))) THEN
            RAISE EXCEPTION 'Close child device bindings before closing EMS period' USING ERRCODE='23514';
        END IF;
    ELSIF TG_TABLE_NAME='device_binding' THEN
        IF (NEW.binding_period_id,NEW.scope,NEW.cabinet_no,NEW.role,NEW.local_no,NEW.device_id,NEW.valid_from) IS DISTINCT FROM
        (OLD.binding_period_id,OLD.scope,OLD.cabinet_no,OLD.role,OLD.local_no,OLD.device_id,OLD.valid_from) OR
        EXISTS(SELECT 1 FROM point_binding WHERE device_binding_id=NEW.id AND NOT(tstzrange(valid_from,valid_to,'[)') <@ tstzrange(NEW.valid_from,NEW.valid_to,'[)'))) THEN
            RAISE EXCEPTION 'Binding identity is immutable; close child point bindings first' USING ERRCODE='23514';
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_gateway_identity BEFORE UPDATE ON ems_gateway FOR EACH ROW EXECUTE FUNCTION check_ems_parent_change();
CREATE TRIGGER ems_point_asset_identity BEFORE UPDATE OF device_id ON measurement_point FOR EACH ROW EXECUTE FUNCTION check_ems_parent_change();
CREATE TRIGGER ems_period_children BEFORE UPDATE ON ems_binding_period FOR EACH ROW EXECUTE FUNCTION check_ems_parent_change();
CREATE TRIGGER ems_binding_children BEFORE UPDATE ON device_binding FOR EACH ROW EXECUTE FUNCTION check_ems_parent_change();


-- Source definition identity cannot change beneath historical bindings or typed values.
CREATE FUNCTION check_ems_definition_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (NEW.catalog_version,NEW.namespace,NEW.source_id,NEW.value_type) IS DISTINCT FROM
    (OLD.catalog_version,OLD.namespace,OLD.source_id,OLD.value_type) THEN
        RAISE EXCEPTION 'Point definition identity is immutable; create a new catalog version' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_definition_identity BEFORE UPDATE ON point_definition FOR EACH ROW EXECUTE FUNCTION check_ems_definition_identity();

-- Aggregate only persisted evidence; no fabricated Kafka lag or successful-send metric.
CREATE VIEW ems_ingestion_status AS
 SELECT r.ems_uuid,r.binding_period_id,p.station_id,
        count(*) AS saved_objects,
        count(*) FILTER (WHERE r.status='projected') AS projected_objects,
        count(*) FILTER (WHERE r.status='projection_failed') AS projection_failures,
        count(*) FILTER (WHERE r.type='important_history') AS saved_history_parts,
        max(r.received_at) AS last_saved_at
 FROM reliable_message r
 JOIN ems_binding_period p ON p.id=r.binding_period_id
 GROUP BY r.ems_uuid,r.binding_period_id,p.station_id;

-- Worker acceptance and management period edits share the gateway advisory lock.
-- Invoker-rights reads here need SELECT only; no worker asset UPDATE privilege.
CREATE FUNCTION check_ems_version_acceptance() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    period ems_binding_period;
    version_ems uuid;
BEGIN
    SELECT * INTO period FROM ems_binding_period WHERE id=NEW.binding_period_id;
    IF period.id IS NULL THEN
        RAISE EXCEPTION 'Acceptance binding period missing' USING ERRCODE='23503';
    END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended(period.ems_uuid::text,78291029));
    SELECT * INTO period FROM ems_binding_period WHERE id=NEW.binding_period_id;
    IF NEW.received_at<period.valid_from OR
       (period.valid_to IS NOT NULL AND NEW.received_at>=period.valid_to) THEN
        RAISE EXCEPTION 'Receipt outside binding period' USING ERRCODE='23514';
    END IF;
    IF TG_TABLE_NAME='structure_acceptance' THEN
        SELECT ems_uuid INTO version_ems FROM structure_revision WHERE id=NEW.revision_id;
    ELSE
        SELECT ems_uuid INTO version_ems FROM config_revision WHERE id=NEW.revision_id;
    END IF;
    IF version_ems IS DISTINCT FROM period.ems_uuid THEN
        RAISE EXCEPTION 'Accepted version EMS mismatch' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_structure_acceptance BEFORE INSERT ON structure_acceptance
    FOR EACH ROW EXECUTE FUNCTION check_ems_version_acceptance();
CREATE TRIGGER ems_config_acceptance BEFORE INSERT ON config_acceptance
    FOR EACH ROW EXECUTE FUNCTION check_ems_version_acceptance();

CREATE FUNCTION check_ems_immutable_version_fact() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'Version content and acceptance facts are immutable' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER ems_structure_immutable BEFORE UPDATE ON structure_revision
    FOR EACH ROW EXECUTE FUNCTION check_ems_immutable_version_fact();
CREATE TRIGGER ems_config_immutable BEFORE UPDATE ON config_revision
    FOR EACH ROW EXECUTE FUNCTION check_ems_immutable_version_fact();
CREATE TRIGGER ems_config_value_immutable BEFORE UPDATE ON config_value
    FOR EACH ROW EXECUTE FUNCTION check_ems_immutable_version_fact();
CREATE TRIGGER ems_bmu_layout_immutable BEFORE UPDATE ON bmu_layout
    FOR EACH ROW EXECUTE FUNCTION check_ems_immutable_version_fact();
CREATE TRIGGER ems_structure_acceptance_immutable BEFORE UPDATE ON structure_acceptance
    FOR EACH ROW EXECUTE FUNCTION check_ems_immutable_version_fact();
CREATE TRIGGER ems_config_acceptance_immutable BEFORE UPDATE ON config_acceptance
    FOR EACH ROW EXECUTE FUNCTION check_ems_immutable_version_fact();
