-- Refresh work exists independently of an observed alarm_current snapshot.
CREATE TABLE alarm_refresh_demand (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 binding_period_id bigint NOT NULL REFERENCES ems_binding_period,
 cabinet_no smallint CHECK(cabinet_no BETWEEN 1 AND 30),
 pending boolean NOT NULL DEFAULT true,
 UNIQUE NULLS NOT DISTINCT(binding_period_id,cabinet_no)
);
ALTER TABLE alarm_current_snapshot DROP COLUMN refresh_required;
-- Never infer historical station provenance from today's gateway station.
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM alarm_current_snapshot) THEN
  RAISE EXCEPTION 'Verify existing alarm snapshot binding provenance before V12';
 END IF;
END $$;
ALTER TABLE alarm_current_snapshot ADD COLUMN binding_period_id bigint NOT NULL;
ALTER TABLE alarm_current_snapshot ADD FOREIGN KEY(binding_period_id,ems_uuid) REFERENCES ems_binding_period(id,ems_uuid);

CREATE FUNCTION ems_valid_history_value(value jsonb) RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE WHEN jsonb_typeof(value) IN ('number','string','boolean','null') THEN true
 WHEN jsonb_typeof(value)='array' THEN NOT EXISTS(
  SELECT 1 FROM jsonb_array_elements(value) item
  WHERE jsonb_typeof(item) NOT IN ('number','string','boolean','null'))
 ELSE false END
$$;
ALTER TABLE history_sample_identity DROP CONSTRAINT history_sample_identity_canonical_value_check;
ALTER TABLE history_sample_identity ADD CHECK(ems_valid_history_value(canonical_value));
