CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE organization (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(120) NOT NULL CHECK(btrim(name)<>''),
 parent_id bigint REFERENCES organization(id),
 CHECK(parent_id IS DISTINCT FROM id),
 UNIQUE NULLS NOT DISTINCT(parent_id,name)
);
CREATE FUNCTION check_organization_cycle() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 -- Serialize hierarchy edits, including concurrent reparenting.
 PERFORM pg_advisory_xact_lock(78291001);
 IF NEW.parent_id IS NOT NULL AND EXISTS (
  WITH RECURSIVE ancestors AS (
   SELECT id,parent_id FROM organization WHERE id=NEW.parent_id
   UNION SELECT o.id,o.parent_id FROM organization o JOIN ancestors a ON o.id=a.parent_id
  ) SELECT 1 FROM ancestors WHERE id=NEW.id
 ) THEN RAISE EXCEPTION 'organization cycle' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER organization_cycle BEFORE INSERT OR UPDATE OF parent_id ON organization FOR EACH ROW EXECUTE FUNCTION check_organization_cycle();

CREATE TABLE app_user (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account varchar(120) NOT NULL UNIQUE CHECK(account=lower(btrim(account)) AND account<>''),
 display_name varchar(120) NOT NULL CHECK(btrim(display_name)<>''),
 password_hash varchar(100) NOT NULL,
 organization_id bigint REFERENCES organization(id),
 enabled boolean NOT NULL DEFAULT true
);
CREATE TABLE app_role(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code varchar(60) NOT NULL UNIQUE,name varchar(120) NOT NULL);
CREATE TABLE permission(code varchar(100) PRIMARY KEY,name varchar(120) NOT NULL);
CREATE TABLE user_role(user_id bigint REFERENCES app_user(id) ON DELETE CASCADE,role_id bigint REFERENCES app_role(id),PRIMARY KEY(user_id,role_id));
CREATE TABLE role_permission(role_id bigint REFERENCES app_role(id) ON DELETE CASCADE,permission_code varchar(100) REFERENCES permission(code),PRIMARY KEY(role_id,permission_code));
CREATE TABLE user_totp(user_id bigint PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,secret_ciphertext text NOT NULL,last_counter bigint);
CREATE TABLE customer(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar(160) NOT NULL UNIQUE);
CREATE TABLE station (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code varchar(60) NOT NULL UNIQUE CHECK(btrim(code)<>''),
 name varchar(160) NOT NULL CHECK(btrim(name)<>''),
 customer_id bigint REFERENCES customer(id),
 organization_id bigint REFERENCES organization(id),
 manager_id bigint REFERENCES app_user(id),
 rated_power_kw numeric(14,3) NOT NULL CHECK(rated_power_kw>0),
 capacity_kwh numeric(14,3) NOT NULL CHECK(capacity_kwh>0),
 asset_type varchar(20) NOT NULL DEFAULT 'BESS' CHECK(asset_type IN ('BESS','PV','Wind','Hybrid','Diesel')),
 region varchar(80),address varchar(300),
 longitude numeric(10,7) CHECK(longitude BETWEEN -180 AND 180),
 latitude numeric(10,7) CHECK(latitude BETWEEN -90 AND 90)
);
CREATE TABLE user_station(user_id bigint REFERENCES app_user(id) ON DELETE CASCADE,station_id bigint REFERENCES station(id),PRIMARY KEY(user_id,station_id));
CREATE TABLE device_model (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 manufacturer varchar(120) NOT NULL,name varchar(120) NOT NULL,
 category varchar(30) NOT NULL CHECK(category IN ('BMS','BESS','PCS','HVAC','MTR','FSS','PV','OTHER')),
 UNIQUE(manufacturer,name)
);
CREATE TABLE device (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 station_id bigint NOT NULL REFERENCES station(id),
 model_id bigint REFERENCES device_model(id),
 code varchar(80) NOT NULL,name varchar(120) NOT NULL,serial_number varchar(120) UNIQUE,
 UNIQUE(station_id,code)
);
CREATE TABLE measurement_kind(code varchar(60) PRIMARY KEY,name varchar(120) NOT NULL,unit varchar(30) NOT NULL);
CREATE TABLE measurement_point (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 device_id bigint NOT NULL REFERENCES device(id),
 kind_code varchar(60) NOT NULL REFERENCES measurement_kind(code),
 code varchar(80) NOT NULL,
 UNIQUE(device_id,code)
);
CREATE TABLE topology_connection (
 source_device_id bigint REFERENCES device(id),target_device_id bigint REFERENCES device(id),
 PRIMARY KEY(source_device_id,target_device_id),CHECK(source_device_id<>target_device_id)
);
CREATE TABLE device_observation (
 device_id bigint PRIMARY KEY REFERENCES device(id),observed_at timestamptz NOT NULL,
 communication_status varchar(20) NOT NULL CHECK(communication_status IN ('online','offline')),
 health_score numeric(5,2) CHECK(health_score BETWEEN 0 AND 100),firmware_version varchar(80)
);
CREATE TABLE audit_event (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actor_id bigint REFERENCES app_user(id),
 action varchar(100) NOT NULL,occurred_at timestamptz NOT NULL DEFAULT now(),detail text NOT NULL
);
CREATE INDEX audit_event_time ON audit_event(occurred_at DESC);
CREATE INDEX device_station ON device(station_id);
CREATE INDEX point_device ON measurement_point(device_id);
CREATE TABLE user_preference (
 user_id bigint REFERENCES app_user(id) ON DELETE CASCADE,
 preference_key varchar(80),preference_value text NOT NULL,
 PRIMARY KEY(user_id,preference_key)
);
