CREATE TABLE alarm (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 device_id bigint NOT NULL REFERENCES device(id),code varchar(80) NOT NULL,title varchar(200) NOT NULL,
 severity varchar(20) NOT NULL CHECK(severity IN ('critical','warning','info')),
 occurred_at timestamptz NOT NULL,recovered_at timestamptz,
 acknowledged_by bigint REFERENCES app_user(id),acknowledged_at timestamptz,
 sla_due_at timestamptz,
 CHECK(recovered_at IS NULL OR recovered_at>=occurred_at),
 CHECK((acknowledged_by IS NULL)=(acknowledged_at IS NULL)),
 UNIQUE(device_id,code,occurred_at)
);
CREATE INDEX alarm_device_time ON alarm(device_id,occurred_at DESC);
CREATE TABLE alarm_note(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,alarm_id bigint NOT NULL REFERENCES alarm(id),author_id bigint NOT NULL REFERENCES app_user(id),body text NOT NULL CHECK(btrim(body)<>''),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE work_order (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id bigint NOT NULL REFERENCES station(id),
 title varchar(200) NOT NULL CHECK(btrim(title)<>''),description text NOT NULL,
 status varchar(20) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','completed','cancelled')),
 created_by bigint NOT NULL REFERENCES app_user(id),assigned_to bigint REFERENCES app_user(id),
 created_at timestamptz NOT NULL DEFAULT now(),due_at timestamptz,completed_at timestamptz,
 CHECK(due_at IS NULL OR due_at>=created_at),
 CHECK((status='completed')=(completed_at IS NOT NULL))
);
CREATE TABLE work_order_alarm(work_order_id bigint REFERENCES work_order(id),alarm_id bigint REFERENCES alarm(id),PRIMARY KEY(work_order_id,alarm_id));
CREATE TABLE work_order_event(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,work_order_id bigint NOT NULL REFERENCES work_order(id),actor_id bigint NOT NULL REFERENCES app_user(id),action varchar(40) NOT NULL,note text NOT NULL,occurred_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE inspection (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id bigint NOT NULL REFERENCES station(id),
 title varchar(200) NOT NULL,due_at timestamptz NOT NULL,assigned_to bigint REFERENCES app_user(id),
 status varchar(20) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','completed','cancelled')),
 completed_at timestamptz,result text,
 CHECK((status='completed')=(completed_at IS NOT NULL)),CHECK(status<>'completed' OR btrim(result)<>'')
);
CREATE TABLE firmware_task (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,device_id bigint NOT NULL REFERENCES device(id),
 target_version varchar(80) NOT NULL,status varchar(20) NOT NULL CHECK(status IN ('pending','running','succeeded','failed')),
 updated_at timestamptz NOT NULL
);
CREATE TABLE operating_plan (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id bigint NOT NULL REFERENCES station(id),
 service_date date NOT NULL,version integer NOT NULL CHECK(version>0),
 kind varchar(20) NOT NULL CHECK(kind IN ('dayAhead','intraday')),
 status varchar(20) NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','approved','rejected','withdrawn')),
 created_by bigint NOT NULL REFERENCES app_user(id),created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(station_id,service_date,version)
);
CREATE TABLE plan_period (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,plan_id bigint NOT NULL REFERENCES operating_plan(id) ON DELETE CASCADE,
 start_minute integer NOT NULL CHECK(start_minute>=0),end_minute integer NOT NULL CHECK(end_minute<=1440 AND end_minute>start_minute),
 mode varchar(20) NOT NULL CHECK(mode IN ('charge','discharge','standby')),
 power_kw numeric(14,3) NOT NULL CHECK(power_kw>=0),CHECK(mode<>'standby' OR power_kw=0),
 EXCLUDE USING gist(plan_id WITH =,int4range(start_minute,end_minute,'[)') WITH &&)
);
CREATE TABLE tariff (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar(120) NOT NULL,
 currency char(3) NOT NULL CHECK(currency ~ '^[A-Z]{3}$')
);
CREATE TABLE tariff_period (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tariff_id bigint NOT NULL REFERENCES tariff(id) ON DELETE CASCADE,
 start_minute integer NOT NULL CHECK(start_minute>=0),end_minute integer NOT NULL CHECK(end_minute<=1440 AND end_minute>start_minute),
 band varchar(20) NOT NULL CHECK(band IN ('peak','flat','valley','superPeak')),
 price_per_kwh numeric(14,6) NOT NULL,
 EXCLUDE USING gist(tariff_id WITH =,int4range(start_minute,end_minute,'[)') WITH &&)
);
CREATE TABLE station_tariff (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id bigint NOT NULL REFERENCES station(id),tariff_id bigint NOT NULL REFERENCES tariff(id),
 valid_from date NOT NULL,valid_until date NOT NULL CHECK(valid_until>valid_from),
 EXCLUDE USING gist(station_id WITH =,daterange(valid_from,valid_until,'[)') WITH &&)
);
CREATE TABLE approval (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,title varchar(200) NOT NULL,
 submitter_id bigint NOT NULL REFERENCES app_user(id),reviewer_id bigint REFERENCES app_user(id),
 submitted_at timestamptz NOT NULL DEFAULT now(),reviewed_at timestamptz,
 status varchar(20) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected','withdrawn')),
 note text,work_order_id bigint REFERENCES work_order(id),plan_id bigint REFERENCES operating_plan(id),
 CHECK(num_nonnulls(work_order_id,plan_id)=1),
 CHECK(status NOT IN ('approved','rejected') OR (reviewer_id IS NOT NULL AND reviewed_at IS NOT NULL)),
 CHECK(reviewer_id IS NULL OR reviewer_id<>submitter_id)
);
CREATE UNIQUE INDEX approval_pending_order ON approval(work_order_id) WHERE status='pending';
CREATE UNIQUE INDEX approval_pending_plan ON approval(plan_id) WHERE status='pending';
CREATE INDEX work_order_station ON work_order(station_id,status);
CREATE INDEX inspection_station ON inspection(station_id,due_at);
