CREATE TABLE market_area(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code varchar(60) NOT NULL UNIQUE,name varchar(120) NOT NULL);
CREATE TABLE market_qualification (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id bigint NOT NULL REFERENCES station(id),area_id bigint NOT NULL REFERENCES market_area(id),
 kind varchar(20) NOT NULL CHECK(kind IN ('response','arbitrage','reserve','vpp')),
 status varchar(20) NOT NULL CHECK(status IN ('valid','pending','expired','suspended')),
 valid_until date,reference varchar(120),UNIQUE(station_id,area_id,kind)
);
CREATE TABLE market_service (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,area_id bigint NOT NULL REFERENCES market_area(id),
 event_code varchar(100) NOT NULL,name varchar(160) NOT NULL,kind varchar(20) NOT NULL CHECK(kind IN ('response','arbitrage','reserve','vpp')),
 starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL CHECK(ends_at>starts_at),
 status varchar(20) NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','confirmed','running','completed','cancelled')),
 UNIQUE(area_id,event_code)
);
CREATE TABLE market_allocation (
 service_id bigint REFERENCES market_service(id),station_id bigint REFERENCES station(id),
 capacity_kw numeric(14,3) NOT NULL CHECK(capacity_kw>0),estimated_revenue numeric(18,2),
 PRIMARY KEY(service_id,station_id)
);
CREATE TABLE contract (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,code varchar(100) NOT NULL UNIQUE,
 customer_id bigint REFERENCES customer(id),currency char(3) NOT NULL CHECK(currency ~ '^[A-Z]{3}$')
);
CREATE TABLE settlement_record (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,station_id bigint NOT NULL REFERENCES station(id),contract_id bigint NOT NULL REFERENCES contract(id),
 reference varchar(120) NOT NULL UNIQUE,recognition_date date NOT NULL,
 status varchar(20) NOT NULL CHECK(status IN ('metered','calculated','reviewing','settled','disputed','unknown')),
 statement_amount numeric(18,2),estimated_amount numeric(18,2),
 meter_complete boolean,calculation_complete boolean
);
CREATE TABLE settlement_line (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,record_id bigint NOT NULL REFERENCES settlement_record(id),
 category varchar(30) NOT NULL CHECK(category IN ('arbitrage','demand','response','gridServices','pv','other','purchase','operating','penalty','adjustment')),
 amount numeric(18,2) NOT NULL,UNIQUE(record_id,category)
);
CREATE TABLE settlement_payment (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,record_id bigint NOT NULL REFERENCES settlement_record(id),
 reference varchar(120) NOT NULL UNIQUE,amount numeric(18,2) NOT NULL,paid_on date NOT NULL
);
CREATE TABLE settlement_review (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,record_id bigint NOT NULL REFERENCES settlement_record(id),
 author_id bigint NOT NULL REFERENCES app_user(id),note text NOT NULL CHECK(btrim(note)<>''),created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO app_role(code,name) VALUES ('owner','电站业主'),('operator','运维人员'),('integrator','安装服务商');
INSERT INTO permission(code,name) VALUES
 ('asset.read','查看资产'),('asset.edit','编辑既有资产'),('telemetry.read','查看遥测'),
 ('alarm.read','查看告警'),('alarm.handle','处理告警'),('workorder.read','查看工单'),('workorder.manage','管理工单'),
 ('inspection.manage','巡检管理'),('approval.review','审批'),('strategy.read','查看计划'),('strategy.manage','编辑计划'),
 ('tariff.manage','电价管理'),('market.read','查看市场服务'),('market.manage','市场草稿'),
 ('revenue.read','查看收益'),('revenue.review','复核收益'),('report.export','导出报告'),
 ('member.manage','组织成员管理'),('audit.read','查看审计');
INSERT INTO role_permission
 SELECT r.id,p.code FROM app_role r CROSS JOIN permission p WHERE
 (r.code='owner' AND p.code IN ('asset.read','telemetry.read','alarm.read','market.read','revenue.read','report.export')) OR
 (r.code='operator' AND p.code IN ('asset.read','telemetry.read','alarm.read','alarm.handle','workorder.read','workorder.manage','inspection.manage','strategy.read','strategy.manage','report.export')) OR
 (r.code='integrator' AND p.code IN ('asset.read','asset.edit','telemetry.read','alarm.read','alarm.handle','workorder.read','workorder.manage','inspection.manage','strategy.read','strategy.manage','tariff.manage','member.manage'));
-- Approval rights require an explicit grant; no default role can approve its own requests.
INSERT INTO measurement_kind(code,name,unit) VALUES
 ('storagePower','储能有功功率','kW'),('loadPower','负荷有功功率','kW'),('pvPower','光伏功率','kW'),
 ('gridPower','电网有功功率','kW'),('soc','荷电状态','%'),('voltage','电压','V'),('current','电流','A'),('temperature','温度','°C');
