-- Schema only. V7 maps existing roles/links without changing V1-V5 history.
ALTER TABLE app_role
 ADD COLUMN organization_id bigint REFERENCES organization(id) ON DELETE RESTRICT,
 ADD COLUMN description text,
 ADD CONSTRAINT app_role_name_not_blank CHECK (btrim(name) <> '');
CREATE UNIQUE INDEX app_role_organization_name
 ON app_role (organization_id, btrim(name)) WHERE organization_id IS NOT NULL;

ALTER TABLE app_user
 ADD COLUMN email varchar(254),
 ADD COLUMN management_organization_id bigint REFERENCES organization(id) ON DELETE RESTRICT;
CREATE INDEX app_user_management_organization ON app_user(management_organization_id);

ALTER TABLE organization
 ADD COLUMN lead_user_id bigint REFERENCES app_user(id) ON DELETE RESTRICT;
CREATE INDEX organization_lead_user ON organization(lead_user_id);

CREATE TABLE member_grant (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
 role_id bigint NOT NULL REFERENCES app_role(id) ON DELETE RESTRICT,
 valid_from timestamptz NOT NULL,
 valid_until timestamptz,
 granted_by bigint REFERENCES app_user(id) ON DELETE RESTRICT,
 CONSTRAINT member_grant_valid_period CHECK (valid_until IS NULL OR valid_until > valid_from)
);
CREATE INDEX member_grant_user ON member_grant(user_id);
CREATE INDEX member_grant_role ON member_grant(role_id);
CREATE INDEX member_grant_grantor ON member_grant(granted_by);

CREATE TABLE member_grant_station (
 grant_id bigint NOT NULL REFERENCES member_grant(id) ON DELETE CASCADE,
 station_id bigint NOT NULL REFERENCES station(id) ON DELETE RESTRICT,
 PRIMARY KEY (grant_id, station_id)
);
CREATE INDEX member_grant_station_station ON member_grant_station(station_id);

COMMENT ON COLUMN app_role.organization_id IS 'Role management owner; NULL is legacy unscoped, never global scope';
COMMENT ON COLUMN app_user.management_organization_id IS 'Independent administrative owner; retained when membership organization_id is cleared';
COMMENT ON COLUMN member_grant.valid_until IS 'Exclusive end instant; NULL means indefinite';
COMMENT ON COLUMN member_grant.granted_by IS 'Actual issuer; NULL preserves unknown historical issuer during legacy migration';
COMMENT ON TABLE member_grant_station IS 'Stations for this grant only; an empty set never means all stations';
