import { useState } from "react"
import { useAuth } from "@/auth/AuthContext"
import { saveBlob } from "./apiAnalytics"
export type PlatformAuditRow = { id:number; actor_id:number|null; action:string; occurred_at:string; detail:string }
export default function PlatformAuditPanel({rows}:{rows:PlatformAuditRow[]}) {
 const {user}=useAuth();const [selected,setSelected]=useState<number|null>(null),[search,setSearch]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[type,setType]=useState(""),[result,setResult]=useState("")
 const filtered=rows.filter(r=>{const day=new Date(r.occurred_at).toLocaleDateString("en-CA",{timeZone:"Asia/Shanghai"});return (!start||day>=start)&&(!end||day<=end)&&(!type||r.action===type)&&!result&&`${r.action} ${r.detail} ${user?.account}`.toLowerCase().includes(search.trim().toLowerCase())})
 const row=rows.find(r=>r.id===selected)
 const exportRows=()=>{const quote=(v:unknown)=>`"${String(v??"").replace(/"/g,'""').replace(/^([=+@-])/,"'$1")}"`;saveBlob(new Blob(["\uFEFF",[["编号","操作时间","操作人ID","操作内容","详情"],...filtered.map(r=>[r.id,r.occurred_at,r.actor_id,r.action,r.detail])].map(r=>r.map(quote).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}),"my-platform-audit.csv")}
 return <section className="platform-audit"><h2>我的审计日志</h2><p className="orgv2-subtext">仅显示当前账号的审计事件。</p>{row?<><button className="orgv2-outline" onClick={()=>setSelected(null)}>返回审计列表</button><h2>{row.action} · 结果未提供</h2><div className="platform-record-grid"><section className="platform-detail-card"><h3>操作记录</h3><dl>{[["操作时间",new Date(row.occurred_at).toLocaleString("zh-CN")],["操作人",user?.account||String(row.actor_id)],["身份","未提供"],["来源IP","未提供"],["请求ID","未提供"]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section><section className="platform-detail-card"><h3>操作对象与判定</h3><dl>{[["客户","未提供"],["站点","未提供"],["请求操作",row.action],["执行结果","未提供"],["操作详情",row.detail]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section></div><p className="orgv2-subtext">接口仅提供操作事件，不能由日志推断设备执行成功或拒绝原因。</p></>:<><div className="platform-toolbar"><label className="platform-audit-date">开始日期<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="platform-audit-date">结束日期<input type="date" value={end} min={start} onChange={e=>setEnd(e.target.value)}/></label><input aria-label="搜索账号 / 操作对象" placeholder="搜索账号 / 操作对象" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="审计操作类型" value={type} onChange={e=>setType(e.target.value)}><option value="">操作类型：全部</option>{[...new Set(rows.map(r=>r.action))].map(t=><option key={t}>{t}</option>)}</select><select aria-label="审计结果" value={result} onChange={e=>setResult(e.target.value)}><option value="">结果：全部（未提供）</option>{["成功","拒绝","失败"].map(r=><option key={r}>{r}</option>)}</select><button className="orgv2-outline" onClick={()=>{setStart("");setEnd("");setSearch("");setType("");setResult("")}}>重置</button><button className="orgv2-outline" disabled={!filtered.length} onClick={exportRows}>导出记录</button></div><section className="platform-table-card"><table><thead><tr>{["操作时间","操作人","操作内容","操作对象","客户","结果","操作"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{new Date(r.occurred_at).toLocaleString("zh-CN")}</td><td>{user?.account}</td><td>{r.action}</td><td title={r.detail}>{r.detail}</td><td>未提供</td><td>未提供</td><td><button className="platform-text-button" onClick={()=>setSelected(r.id)}>查看详情</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="platform-empty">没有符合筛选条件的审计记录</p>}</section></>}</section>
}
