import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from "react"
import { api } from "@/api/client"
import { useAuth } from "@/auth/AuthContext"
import MemberGrantsPanel from "./MemberGrantsPanel"
import type { RolePermissionsHandle } from "./RolePermissionsPanel"
import { platformApi, type MemberGrant } from "./platform/platformApi"
type Member={id:number;display_name:string;account:string;organization_id:number|null;management_organization_id:number;enabled:boolean}
export default forwardRef<RolePermissionsHandle>(function PlatformTemporaryGrants(_,ref){
 const {user}=useAuth();const canManage=!!user?.permissions.includes("member.grant.manage"),canRead=!!user?.permissions.includes("organization.member.read")
 const [members,setMembers]=useState<Member[]>([]),[rows,setRows]=useState<{member:Member;grant:MemberGrant}[]>([]),[selected,setSelected]=useState<number|null>(null),[status,setStatus]=useState(""),[search,setSearch]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[detail,setDetail]=useState<string|null>(null)
 const managed=useRef(new Set<number>()),panel=useRef<RolePermissionsHandle>(null)
 useImperativeHandle(ref,()=>({requestLeave:()=>panel.current?.requestLeave()??Promise.resolve(true)}))
 useEffect(()=>{const controller=new AbortController();setSelected(null);setDetail(null);setRows([]);setMembers([]);setLoading(true);setError("");managed.current=new Set();if(!canManage&&!canRead){setLoading(false);return}
 void(async()=>{try{const [read,write]=await Promise.all([canRead?api<Member[]>("/members",{signal:controller.signal}):[],canManage?api<Member[]>("/members?purpose=grants",{signal:controller.signal}):[]]);const directory=[...new Map([...read,...write].map(m=>[m.id,m])).values()];const grants=await Promise.all(directory.map(async member=>({member,grants:await platformApi.memberGrants(member.id,controller.signal)})));if(controller.signal.aborted)return;managed.current=new Set(write.map(m=>m.id));setMembers(directory);setRows(grants.flatMap(({member,grants})=>grants.filter(g=>g.term!=="permanent"&&g.validUntil!==null&&!g.scopeRestricted).map(grant=>({member,grant}))))}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"授权读取失败")}finally{if(!controller.signal.aborted)setLoading(false)}})();return()=>controller.abort()
 },[user?.id,canManage,canRead,JSON.stringify(user?.organizationPermissions),JSON.stringify(user?.stationPermissions),revision])
 const detailRow=rows.find(r=>`${r.member.id}:${r.grant.id}`===detail)
 const member=members.find(m=>m.id===selected);const filtered=rows.filter(({member,grant})=>(!status||grant.status===status)&&`${member.display_name} ${member.account} ${grant.stations.map(s=>s.name).join(" ")}`.includes(search))
 return member?<MemberGrantsPanel ref={panel} member={member} organizationName="当前可见组织范围" canManage={canManage&&managed.current.has(member.id)} accessState="ready" selfSelected={String(member.id)===String(user?.id)} onClose={()=>{setSelected(null);setRevision(r=>r+1)}}/>:<section className="platform-temporary"><p className="api-context-note">期限授权已连接业务服务。有效期由服务器计算；支持30天、90天、1年及长期。自定义小时、授权原因和审批字段尚未接通。</p><div className="platform-toolbar"><input aria-label="搜索被授权人 / 站点" placeholder="搜索被授权人 / 站点" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="授权状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="">授权状态：全部</option><option value="active">生效中</option><option value="expired">已到期</option><option value="scheduled">未生效</option></select><select aria-label="选择成员分配授权" value="" onChange={e=>setSelected(Number(e.target.value))}><option value="">选择成员查看 / 新增授权</option>{members.map(m=><option key={m.id} value={m.id}>{m.display_name} / {m.account}</option>)}</select></div>{error&&<p role="alert" className="api-inline-error">{error}</p>}<section className="platform-table-card"><table><thead><tr>{["被授权人","所属客户","资产范围","授权内容","有效期至","状态","操作"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(({member,grant})=><tr key={`${member.id}:${grant.id}`}><td>{member.display_name}<small>{member.account}</small></td><td>未提供</td><td>{grant.stations.map(s=>s.name).join("、")||"组织管理范围"}</td><td>{grant.roleName||"角色信息受限"}</td><td>{grant.validUntil?new Date(grant.validUntil).toLocaleString("zh-CN"):"长期"}</td><td>{({active:"生效中",expired:"已到期",scheduled:"未生效",disabled:"已停用"} as Record<string,string>)[grant.status]||grant.status}</td><td><button className="platform-text-button" onClick={()=>setDetail(`${member.id}:${grant.id}`)}>查看</button><button className="platform-text-button" onClick={()=>setSelected(member.id)}>管理授权</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="platform-empty">{loading?"正在读取期限授权…":"暂无当前范围可见的期限授权"}</p>}</section>{detailRow&&<section className="platform-detail-card"><h3>{detailRow.member.display_name} · 授权详情</h3><dl>{[["有效期限",`${detailRow.grant.validFrom?new Date(detailRow.grant.validFrom).toLocaleString("zh-CN"):"未提供"} — ${detailRow.grant.validUntil?new Date(detailRow.grant.validUntil).toLocaleString("zh-CN"):"长期"}`],["授权对象",detailRow.grant.stations.map(s=>s.name).join("、")||"组织管理范围"],["允许操作",detailRow.grant.rolePermissions?.map(p=>p.name).join("、")||"接口未提供"],["控制权限","以角色完整权限和当前站点授权为准"],["授权人","接口未提供"],["授权原因","接口未提供"]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><button className="orgv2-outline" onClick={()=>setSelected(detailRow.member.id)}>查看完整权限 / 编辑 / 撤销</button></section>}</section>
})
