"""Render reviewed SQL from canonical templates; never connects to a database."""
import json
from pathlib import Path


def render():
    root = Path(__file__).resolve().parents[1]
    resources = root / 'src/main/resources'
    catalog = json.loads((resources / 'permission-catalog.json').read_text(encoding='utf-8'))
    available = {entry['code'] for entry in catalog if entry['available']}
    templates = json.loads((resources / 'permission-role-templates.json').read_text(encoding='utf-8'))
    quote = lambda value: "'" + value.replace("'", "''") + "'"
    rows = ',\n'.join(' (' + ','.join(map(quote, (template['code'], code))) + ')'
                     for template in templates for code in template['permissions'] if code in available)
    return """-- Generated by database/generate_template_sync.py; review the diff before explicit execution.
-- Separate operator choice; NOT included by apply.sql and never assigns a member.
\\set ON_ERROR_STOP on
BEGIN;
DO $$ BEGIN
 IF current_database()<>'ems_cloud_v2_proto' THEN RAISE EXCEPTION 'Wrong database'; END IF;
 IF NOT EXISTS(SELECT 1 FROM schema_migration WHERE version=9) THEN RAISE EXCEPTION 'V9 required'; END IF;
END $$;
SELECT pg_advisory_xact_lock(78291002);
SELECT pg_advisory_xact_lock(78291001);
LOCK TABLE app_role,role_permission,member_grant,user_role IN SHARE ROW EXCLUSIVE MODE;
CREATE TEMP TABLE template_sync_desired(template_code text,permission_code text) ON COMMIT DROP;
INSERT INTO template_sync_desired VALUES
""" + rows + """;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM template_sync_desired d LEFT JOIN permission p ON p.code=d.permission_code WHERE p.code IS NULL) THEN
  RAISE EXCEPTION 'Available template permission missing from database';
 END IF;
END $$;
-- Every retained grant excludes the role, including expired/future/disabled recipients.
-- Legacy references exclude it too. Only canonical default codes are eligible.
WITH inserted AS (
 INSERT INTO role_permission(role_id,permission_code)
 SELECT r.id,d.permission_code FROM app_role r JOIN template_sync_desired d
 ON r.code='template_'||d.template_code||'__o'||r.organization_id::text
 OR r.code='org_'||r.organization_id::text||'_'||d.template_code
 WHERE NOT EXISTS(SELECT 1 FROM member_grant g WHERE g.role_id=r.id)
 AND NOT EXISTS(SELECT 1 FROM user_role u WHERE u.role_id=r.id)
 ON CONFLICT DO NOTHING RETURNING role_id,permission_code
), changes AS (
 SELECT jsonb_agg(jsonb_build_object('roleId',role_id,'added',permission_code) ORDER BY role_id,permission_code) detail FROM inserted
)
INSERT INTO audit_event(actor_id,action,detail)
 SELECT NULL,'permission.templates.sync',detail::text FROM changes WHERE detail IS NOT NULL;
COMMIT;
"""


if __name__ == '__main__':
    Path(__file__).with_name('initialize_unassigned_templates.sql').write_text(render(), encoding='utf-8')
