-- Generated by database/generate_template_sync.py; review the diff before explicit execution.
-- Separate operator choice; NOT included by apply.sql and never assigns a member.
\set ON_ERROR_STOP on
BEGIN;
DO $$ BEGIN
 IF current_database()<>'ems_cloud_v2_proto' THEN RAISE EXCEPTION 'Wrong database'; END IF;
 IF NOT EXISTS(SELECT 1 FROM schema_migration WHERE version=9) THEN RAISE EXCEPTION 'V9 required'; END IF;
END $$;
SELECT pg_advisory_xact_lock(78291002);
SELECT pg_advisory_xact_lock(78291001);
LOCK TABLE app_role,role_permission,member_grant,user_role IN SHARE ROW EXCLUSIVE MODE;
CREATE TEMP TABLE template_sync_desired(template_code text,permission_code text) ON COMMIT DROP;
INSERT INTO template_sync_desired VALUES
 ('owner','asset.read'),
 ('owner','revenue.read'),
 ('owner','strategy.read'),
 ('owner','alarm.read'),
 ('owner','workorder.read'),
 ('owner','approval.read'),
 ('owner','report.export'),
 ('pmo','asset.read'),
 ('pmo','revenue.read'),
 ('pmo','strategy.read'),
 ('pmo','alarm.read'),
 ('pmo','workorder.read'),
 ('pmo','approval.read'),
 ('pmo','asset.edit'),
 ('pmo','workorder.create'),
 ('pmo','approval.review'),
 ('ems','asset.read'),
 ('ems','revenue.read'),
 ('ems','strategy.read'),
 ('ems','alarm.read'),
 ('ems','workorder.read'),
 ('ems','approval.read'),
 ('ems','strategy.manage'),
 ('om','asset.read'),
 ('om','strategy.read'),
 ('om','alarm.read'),
 ('om','alarm.handle'),
 ('om','workorder.read'),
 ('om','workorder.create'),
 ('om','workorder.edit'),
 ('om','workorder.handle'),
 ('om','approval.read'),
 ('om','approval.review'),
 ('om','report.export'),
 ('om','organization.member.read'),
 ('epc','asset.read'),
 ('epc','asset.edit'),
 ('epc','strategy.read'),
 ('epc','workorder.read'),
 ('epc','workorder.create'),
 ('epc','workorder.edit'),
 ('vendor','asset.read'),
 ('vendor','alarm.read'),
 ('vendor','workorder.read'),
 ('platform','asset.read'),
 ('platform','asset.edit'),
 ('platform','revenue.read'),
 ('platform','strategy.read'),
 ('platform','strategy.manage'),
 ('platform','alarm.read'),
 ('platform','alarm.handle'),
 ('platform','workorder.read'),
 ('platform','workorder.create'),
 ('platform','workorder.edit'),
 ('platform','workorder.handle'),
 ('platform','approval.read'),
 ('platform','approval.review'),
 ('platform','report.export'),
 ('platform','customer.read'),
 ('platform','customer.manage'),
 ('platform','organization.member.read'),
 ('platform','organization.manage'),
 ('platform','member.manage.profile'),
 ('platform','role.manage'),
 ('platform','member.grant.manage'),
 ('platform','audit.read'),
 ('readonly','asset.read'),
 ('readonly','revenue.read'),
 ('readonly','strategy.read'),
 ('readonly','alarm.read'),
 ('readonly','workorder.read'),
 ('readonly','approval.read');
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM template_sync_desired d LEFT JOIN permission p ON p.code=d.permission_code WHERE p.code IS NULL) THEN
  RAISE EXCEPTION 'Available template permission missing from database';
 END IF;
END $$;
-- Every retained grant excludes the role, including expired/future/disabled recipients.
-- Legacy references exclude it too. Only canonical default codes are eligible.
WITH inserted AS (
 INSERT INTO role_permission(role_id,permission_code)
 SELECT r.id,d.permission_code FROM app_role r JOIN template_sync_desired d
 ON r.code='template_'||d.template_code||'__o'||r.organization_id::text
 OR r.code='org_'||r.organization_id::text||'_'||d.template_code
 WHERE NOT EXISTS(SELECT 1 FROM member_grant g WHERE g.role_id=r.id)
 AND NOT EXISTS(SELECT 1 FROM user_role u WHERE u.role_id=r.id)
 ON CONFLICT DO NOTHING RETURNING role_id,permission_code
), changes AS (
 SELECT jsonb_agg(jsonb_build_object('roleId',role_id,'added',permission_code) ORDER BY role_id,permission_code) detail FROM inserted
)
INSERT INTO audit_event(actor_id,action,detail)
 SELECT NULL,'permission.templates.sync',detail::text FROM changes WHERE detail IS NOT NULL;
COMMIT;
