import {useEffect,useState} from 'react'
import {useAuth} from '@/auth/AuthContext'
import {hasStationPermission} from '@/auth/apiPermissions'
import {DEMO_MODE} from '@/api/client'
import {type RegisterLeaveGuard} from '../useEditorLeaveGuard'
import {useWorkflowLeave,workflowKey} from './WorkflowEditor'
type Task={id:string;title:string;domain:string;status:string;owner:string;due?:string;stationId:string}
const tabs=['全部任务','执行任务','异常待接管','任务编排','消息中心','协作与交接'] as const
type Tab=typeof tabs[number]
const empty={object:'',stage:'准备',evidence:'',soc:'',threshold:'',rollback:'',responsibility:'',reason:'',name:'',condition:'',branch:'',context:'',unresolved:'',receiver:'',subscription:'',merge:'5',ack:false}
export function TaskWorkbench({stations,tasks,registerLeaveGuard,onClose,onOpen}:{stations:{id:string;name:string}[];tasks:Task[];registerLeaveGuard?:RegisterLeaveGuard;onClose:()=>void;onOpen:(id:string,domain:string)=>void}){
 const {user}=useAuth();const [tab,setTab]=useState<Tab>('全部任务'),[station,setStation]=useState(stations[0]?.id||''),[search,setSearch]=useState(''),[draft,setDraft]=useState(empty),[baseline,setBaseline]=useState(empty),[notice,setNotice]=useState(''),[error,setError]=useState(''),[nodes,setNodes]=useState(['触发','范围校核','安全复核','执行','验证','交接','关闭']),[savedNodes,setSavedNodes]=useState(nodes)
 const key=workflowKey(user?.id||'',station,'tasks',tab),canEdit=DEMO_MODE||hasStationPermission(user,station,'workorder.edit')||hasStationPermission(user,station,'workorder.handle')
 const reset=()=>{setDraft(baseline);setNodes(savedNodes);setError('')}
 const leave=useWorkflowLeave(JSON.stringify(draft)!==JSON.stringify(baseline)||JSON.stringify(nodes)!==JSON.stringify(savedNodes),registerLeaveGuard,reset,key,canEdit)
 useEffect(()=>{if(!stations.some(s=>s.id===station)){leave.cancelPending();setStation(stations[0]?.id||'');setDraft(empty);setBaseline(empty)}},[stations.map(s=>s.id).join('|')])
 useEffect(()=>{try{const data=JSON.parse(localStorage.getItem(key)||'null');setDraft(data?.draft||empty);setBaseline(data?.draft||empty);const n=data?.nodes||['触发','范围校核','安全复核','执行','验证','交接','关闭'];setNodes(n);setSavedNodes(n);setNotice('');setError('')}catch{setError('草稿读取失败')}},[key])
 const change=(field:keyof typeof empty,value:string|boolean)=>{setDraft(d=>({...d,[field]:value}));setNotice('');setError('')}
 const field=(id:keyof typeof empty,label:string,multi=false)=><label key={id}>{label}{multi?<textarea aria-label={label} value={String(draft[id])} disabled={!canEdit} onChange={e=>change(id,e.target.value)}/>:<input aria-label={label} value={String(draft[id])} disabled={!canEdit} onChange={e=>change(id,e.target.value)}/>}</label>
 function save(){if(!canEdit)return;const required=tab==='执行任务'?['object','evidence']:tab==='异常待接管'?['object','responsibility','reason']:tab==='任务编排'?['name','condition','branch']:tab==='消息中心'?['subscription']:['context','unresolved','responsibility','receiver'];if(required.some(k=>!String(draft[k as keyof typeof empty]).trim())){setError('请填写完整的对象、责任与必填内容');return}if(tab==='任务编排'&&(!nodes.includes('关闭')||!nodes.includes('安全复核'))){setError('编排必须包含安全复核及关闭节点');return}if(tab==='执行任务'&&(Number(draft.soc)<0||Number(draft.soc)>100)){setError('SOC 下限应在 0–100% 之间');return}try{localStorage.setItem(key,JSON.stringify({draft,nodes}));setBaseline(draft);setSavedNodes(nodes);setNotice('本地草稿已保存；尚未发布、执行、发送或接管')}catch{setError('保存失败：本地存储不可用')}}
 const visible=tasks.filter(t=>(!station||t.stationId===station)&&`${t.id} ${t.title} ${t.owner}`.includes(search)),exceptions=visible.filter(t=>!t.owner||(t.due&&Date.parse(t.due)<Date.now()&&!['已完成','已通过','已驳回','已取消'].includes(t.status)))
 const table=(list:Task[],exception=false)=><div className="wo-task-table"><table><thead><tr>{(exception?['异常任务','状态','来源','持续时间','操作']:['任务 / 业务域','阶段','负责人','截止时间','操作']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{list.map(t=><tr key={`${t.domain}:${t.id}`}><td>{t.id} · {t.title}</td><td>{exception?(!t.owner?'无人负责':'已超时'):t.status}</td><td>{exception?t.domain:(t.owner||'未分派')}</td><td>{exception?'未提供':t.due?new Date(t.due).toLocaleString():'未提供'}</td><td><button className="work-orders-link" onClick={()=>void leave.requestLeave().then(ok=>{if(ok)onOpen(t.id,t.domain)})}>查看详情</button></td></tr>)}</tbody></table>{!list.length&&<p className="operations-empty">暂无符合条件的{exception?'异常':'任务'}；其他业务域尚未接通。</p>}</div>
 return <section className="wo-workbench"><nav aria-label="任务协作导航">{tabs.map(t=><button key={t} className="operations-button" aria-pressed={tab===t} onClick={()=>void leave.requestLeave().then(ok=>{if(ok)setTab(t)})}>{t}</button>)}<button className="operations-button" onClick={()=>void leave.requestLeave().then(ok=>{if(ok)onClose()})}>返回工单队列</button></nav><h2>{tab}</h2><div className="wo-workbench-filter"><label>业务站点<select aria-label="业务站点" value={station} onChange={e=>{const next=e.target.value;void leave.requestLeave().then(ok=>{if(ok)setStation(next)})}}>{stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><input aria-label="搜索任务" placeholder="搜索、筛选或定位对象" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="wo-workbench-grid"><section>
 {tab==='全部任务'&&<><h3>全量任务清单</h3>{table(visible)}</>}
 {tab==='执行任务'&&<><h3>执行步骤与证据</h3><div className="wo-flow">{['准备','范围确认','安全检查','执行','观察','验证','恢复'].map(s=><button key={s} className="operations-button" aria-pressed={draft.stage===s} onClick={()=>change('stage',s)}>{s}</button>)}</div><div className="wo-task-form">{field('object','任务对象')}{field('evidence','当前步骤证据',true)}{field('soc','SOC 下限（%）')}{field('threshold','异常接管阈值（MW）')}{field('rollback','回滚方案')}</div><p>当前步骤：{draft.stage}。范围、版本与安全复核结果需人工记录，未连接控制执行服务。</p></>}
 {tab==='异常待接管'&&<><h3>异常与接管队列</h3>{table(exceptions,true)}<div className="wo-task-form">{field('object','异常任务编号')}{field('responsibility','接管责任人')}{field('reason','异常原因及复核意见',true)}{field('rollback','接管回滚方案')}</div></>}
 {tab==='任务编排'&&<><h3>任务编排画布 · 本地草案</h3><div className="wo-flow">{nodes.map((n,i)=><span key={i}>{n}<button aria-label={`删除节点 ${i+1}`} disabled={!canEdit} onClick={()=>setNodes(nodes.filter((_,j)=>j!==i))}>×</button>{i>0&&<button aria-label={`上移节点 ${i+1}`} onClick={()=>{const next=[...nodes];[next[i-1],next[i]]=[next[i],next[i-1]];setNodes(next)}}>←</button>}</span>)}</div><button className="operations-button" disabled={!canEdit} onClick={()=>setNodes([...nodes,'条件分支'])}>添加阶段</button><div className="wo-task-form">{field('name','模板名称')}{field('condition','触发条件')}{field('responsibility','阶段责任人')}{field('branch','异常分支与闭合条件',true)}</div></>}
 {tab==='消息中心'&&<><h3>消息与通知</h3><table><thead><tr>{['消息主题','来源','对象','时间','状态'].map(v=><th key={v}>{v}</th>)}</tr></thead></table><p className="operations-empty">暂无消息数据，通知服务尚未接通。</p><div className="wo-task-form">{field('subscription','订阅规则')}{field('merge','同对象归并窗口（分钟）')}<label><input type="checkbox" checked={draft.ack} disabled={!canEdit} onChange={e=>change('ack',e.target.checked)}/>需要接收确认</label></div></>}
 {tab==='协作与交接'&&<><h3>跨域协作与交接关系</h3><div className="wo-flow">{['运营 · 偏差事件','任务中心 · 交接包','运维 · 工单处理','厂家 · 诊断意见'].map(v=><span key={v}>{v}</span>)}</div><h3>未结事项与接收</h3><div className="wo-task-form">{field('context','交接上下文',true)}{field('unresolved','未结事项',true)}{field('responsibility','交接责任人')}{field('receiver','接收人')}{field('evidence','证据包与时间线',true)}<label><input type="checkbox" checked={draft.ack} disabled={!canEdit} onChange={e=>change('ack',e.target.checked)}/>记录本地接收确认</label></div></>}
 </section><aside><h3>{tab==='全部任务'?'范围与状态分布':tab==='执行任务'?'保护与接管':tab==='异常待接管'?'接管保护':tab==='任务编排'?'模板版本与校验':tab==='消息中心'?'订阅与确认':'交接事实与证据'}</h3>{(tab==='全部任务'?[['按业务域',`${visible.filter(t=>t.domain==='工单').length} 工单 / ${visible.filter(t=>t.domain==='审批').length} 审批`],['按阶段',`${visible.filter(t=>t.status==='处理中').length} 执行中`],['无人负责',String(visible.filter(t=>!t.owner).length)],['已超时',String(exceptions.length)]]:tab==='异常待接管'?[['未知态禁令','不可继续或自动关闭'],['接管责任',draft.responsibility||'未指定'],['需要复核','未接通'],['回滚可用',draft.rollback||'未记录']]:tab==='任务编排'?[['当前草案','仅本机'],['生产生效','未接通'],['权限检查','提交前需服务端复核'],['测试运行','未接通']]:[['数据来源','本地记录'],['服务状态','尚未接通'],['证据',draft.evidence||'未记录'],['接收确认',draft.ack?'已勾选（本地）':'未确认']]).map(([a,b])=><dl key={a}><dt>{a}</dt><dd>{b}</dd></dl>)}</aside></div>{tab!=='全部任务'&&<footer><p className="wo-boundary">此功能尚未接通后台；草稿按当前账号、模式、站点及业务类型隔离。</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button className="operations-button work-orders-approve" disabled={!canEdit} onClick={save}>检查并保存本地草稿</button></footer>}{leave.dialog}</section>
}
