import {useCallback,useEffect,useRef,useState} from "react"
import type {Station} from "@/App"
import {useAuth} from "@/auth/AuthContext"
import {hasStationPermission} from "@/auth/apiPermissions"
import {DEMO_MODE,send} from "@/api/client"
import {exportOperationsCsv} from "@/data/operations"
import {formatPoint} from "@/data/stationDevices"
import {WORK_ORDER_STATUS,INSPECTION_STATUS} from "@/data/stationMaintenance"
import type {RegisterLeaveGuard} from "../useEditorLeaveGuard"
import {Modal} from "../station-provision/Common"
import {DataTable,DraftRecords,EmptyChart,Surface,useMaintenanceDraft,type Draft} from "./MaintenanceDraft"
import "./maintenance-workbench.css"

const tools=[['plan','维护计划','inspection.manage'],['inspection','巡检管理','inspection.manage'],['spares','备件管理','asset.read'],['repair','维修工单','workorder.read'],['diagnostics','远程诊断','asset.read'],['health','健康分析','asset.read']] as const
type Tool=typeof tools[number][0]
type Props={stations:Station[],registerLeaveGuard?:RegisterLeaveGuard,onServerChange?:()=>void,onOpenOrders?:(id:string,orderId?:string)=>void,onHealthDevice?:(stationId:string,deviceId:string)=>void}
export default function MaintenanceWorkbench({stations,registerLeaveGuard,onServerChange,onOpenOrders,onHealthDevice}:Props){
 const {user}=useAuth(),[tool,setTool]=useState<Tool>('inspection'),[stationId,setStationId]=useState(stations[0]?.id||''),[revoked,setRevoked]=useState(false)
 const visible=tools.filter(t=>DEMO_MODE||stations.some(s=>hasStationPermission(user,s.id,t[2])))
 const selected=visible.find(t=>t[0]===tool)||visible[0]
 const permitted=stations.filter(s=>DEMO_MODE||hasStationPermission(user,s.id,selected?.[2]||'asset.read'))
 const station=permitted.find(s=>s.id===stationId)
 const guard=useRef<null|(()=>Promise<boolean>)>(null)
 const register=useCallback<RegisterLeaveGuard>(g=>{guard.current=g;registerLeaveGuard?.(g)},[registerLeaveGuard])
 const leave=(next:()=>void)=>{void(async()=>{if(await(guard.current?.()??Promise.resolve(true)))next()})()}
 useEffect(()=>{if(stationId&&!station){setStationId('');setRevoked(true)}},[stationId,station])
 return <div className="maintenance-workbench"><nav className="maintenance-tool-nav" aria-label="运维工具导航">{visible.map(t=><button key={t[0]} aria-current={selected?.[0]===t[0]?'page':undefined} onClick={()=>leave(()=>{setTool(t[0]);setStationId(stations.find(s=>DEMO_MODE||hasStationPermission(user,s.id,t[2]))?.id||'');setRevoked(false)})}>{t[1]}</button>)}</nav>
 <div className="maintenance-tool-scope"><label>责任站点<select aria-label="工具站点" value={stationId} onChange={e=>{const id=e.target.value;leave(()=>{setStationId(id);setRevoked(false)})}}><option value="">请选择授权站点</option>{permitted.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><span>已接通数据沿用业务服务；未接通功能仅保存本机草稿</span></div>
 {revoked&&<p role="alert">当前站点权限已撤销，请重新选择授权站点。</p>}
 {station&&selected?<ToolContent key={`${DEMO_MODE}:${user?.id}:${station.id}:${selected[0]}`} tool={selected[0]} station={station} stations={permitted} registerLeaveGuard={register} onServerChange={onServerChange} onOpenOrders={onOpenOrders} onHealthDevice={onHealthDevice}/>:<div className="operations-empty">请选择具有当前工具权限的站点</div>}
 </div>
}
function ToolContent({tool,station,stations,registerLeaveGuard,onServerChange,onOpenOrders,onHealthDevice}:Props&{tool:Tool,station:Station}){
 const {user}=useAuth(),[query,setQuery]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[view,setView]=useState('list'),[form,setForm]=useState(false),[editingId,setEditingId]=useState(''),[priority,setPriority]=useState(''),[detail,setDetail]=useState<Draft|null>(null),[busy,setBusy]=useState(false)
 const [values,setValues]=useState<Draft>({direction:'入库',quantity:'',part:'',order:'',note:'',title:'',type:tool==='inspection'?'日常巡检':tool==='repair'?'故障维修':'预防性',due:'',owner:user?.id||'',device:'',priority:'重要',items:'',mode:'手动诊断',duration:'60',interval:'5',voltageMin:'',voltageMax:'',temperatureMax:'',socMin:'',socMax:''})
 const [deviceId,setDeviceId]=useState(''),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7))
 const d=useMaintenanceDraft(station.id,tool==='diagnostics'?`diagnostics:${deviceId||'unselected'}`:tool,true,registerLeaveGuard)
 const set=(key:string,value:string)=>{setValues(v=>({...v,[key]:value}));d.setDirty(true);d.setNotice('');d.setError('')}
 const devices=station.deviceInventory||[],device=devices.find(x=>x.id===deviceId)
 const inspections=(station.maintenance?.inspections||[]).filter(i=>(!status||i.status===status)&&(!query||`${i.id} ${i.title} ${i.owner}`.includes(query)))
 const monthInspections=inspections.filter(i=>i.dueAt?.startsWith(new Date().toISOString().slice(0,7)))
 const inspectionRate=monthInspections.length?Math.round(monthInspections.filter(i=>i.status==='completed').length/monthInspections.length*100):null
 const orders=(station.maintenance?.workOrders||[]).filter(o=>(!status||o.status===status)&&(!query||`${o.id} ${o.title} ${o.description}`.includes(query)))
 // The current API has no inspection type, work order priority/type, inventory or diagnostic result fields.
 const filteredInspections=type?[]:inspections,filteredOrders=type||priority?[]:orders
 const text=(label:string,key:string,inputType='text')=><label>{label}<input aria-label={label} type={inputType} value={values[key]||''} onChange={e=>set(key,e.target.value)}/></label>
 const select=(label:string,key:string,options:string[])=><label>{label}<select aria-label={label} value={values[key]||''} onChange={e=>set(key,e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>
 const deviceSelect=<label>设备 / 系统<select aria-label="设备 / 系统" value={values.device} onChange={e=>set('device',e.target.value)}><option value="">请选择已注册设备</option>{devices.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label>
 const feedback=<>{d.error&&<p role="alert">{d.error}</p>}{d.notice&&<p role="status">{d.notice}</p>}</>
 function validate(){
  if(tool==='spares'){
   if(!values.part.trim()||!values.note.trim()){d.setError('请填写备件名称 / 规格及经办备注。');return false}
   if(!Number.isSafeInteger(Number(values.quantity))||Number(values.quantity)<=0){d.setError('申请数量必须为大于 0 的整数。');return false}
  }else if(tool==='diagnostics'){
   if(!device||device.status!=='online'){d.setError('请选择通信在线的已注册设备。');return false}
   if(!Number.isInteger(Number(values.duration))||Number(values.duration)<10||Number(values.duration)>3600||!Number.isInteger(Number(values.interval))||Number(values.interval)<1||Number(values.interval)>Number(values.duration)){d.setError('诊断时长须为 10–3600 秒，采样间隔须为 1 秒至诊断时长。');return false}
   for(const [lo,hi,label] of [['voltageMin','voltageMax','电压'],['socMin','socMax','SOC']]){if((values[lo]||values[hi])&&(!values[lo]||!values[hi]||!Number.isFinite(Number(values[lo]))||!Number.isFinite(Number(values[hi]))||Number(values[lo])<0||Number(values[lo])>=Number(values[hi])||(lo==='socMin'&&Number(values[hi])>100))){d.setError(`${label}上下限无效，请填写有效的递增范围。`);return false}}
   if(values.temperatureMax&&(!Number.isFinite(Number(values.temperatureMax))||Number(values.temperatureMax)<-40||Number(values.temperatureMax)>150)){d.setError('温度上限须为 -40 至 150 °C。');return false}
   if(!values.note.trim()){d.setError('请填写诊断说明。');return false}
  }else{
   if(!values.title.trim()||!values.due||!values.owner.trim()){d.setError('请填写标题、计划时间和负责人。');return false}
   if(!Number.isFinite(Date.parse(values.due))||Date.parse(values.due)<=Date.now()){d.setError('计划时间必须晚于当前时间。');return false}
   if(tool!=='inspection'&&!devices.some(x=>x.id===values.device)){d.setError('请选择已注册设备 / 系统。');return false}
  }
  d.setError('');return true
 }
 function save(){
  if(!validate())return
  const keys=tool==='spares'?['direction','part','quantity','order','note']:tool==='diagnostics'?['mode','duration','interval','voltageMin','voltageMax','temperatureMax','socMin','socMax','note']:tool==='inspection'?['title','type','due','owner','items']:['title','type','device','due','owner','items',...(tool==='repair'?['priority']:[])]
  d.save({...Object.fromEntries(keys.map(key=>[key,values[key]])),...(editingId?{inspectionId:editingId}:{}),...(tool==='diagnostics'?{device:deviceId,deviceName:device?.name||''}:{})})
 }
 async function createInspection(){
  if(!validate()||busy||(!DEMO_MODE&&!hasStationPermission(user,station.id,'inspection.manage')))return
  if(!/^[1-9]\d*$/.test(values.owner)){d.setError('巡检人须填写有效的成员 ID。');return}
  if(DEMO_MODE){d.setError('示例模式不能创建服务器巡检，可保存本地草稿。');return}
  setBusy(true)
  try{await send('/inspections','POST',{stationId:Number(station.id),title:values.title.trim(),dueAt:values.due.replace('T',' ')+':00',assignedTo:Number(values.owner)});d.setDirty(false);setForm(false);d.setNotice('服务器已创建巡检；巡检类型与检查项尚无接口，未提交这些字段。');onServerChange?.()}catch(e){d.setError(e instanceof Error?e.message:'创建失败，请重试')}finally{setBusy(false)}
 }
 const filters=<div className="maintenance-tools-filter"><input aria-label="搜索任务或设备" placeholder="搜索任务、设备…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="任务类型" value={type} onChange={e=>setType(e.target.value)}><option value="">类型：全部</option>{(tool==='inspection'?['日常巡检','专项巡检','节假日巡检']:tool==='repair'?['故障维修','预防性维修']:['预防性','纠正性','预测性']).map(x=><option key={x}>{x}</option>)}</select><select aria-label="任务状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="">状态：全部</option><option value="pending">待执行</option><option value="processing">处理中</option><option value="completed">已完成</option><option value="cancelled">已取消</option></select>{type&&<small>服务器未提供类型字段，未分类记录不匹配类型筛选。</small>}</div>
 const commonForm=<div className="maintenance-draft-form">{text(tool==='inspection'?'巡检标题':tool==='plan'?'计划标题':'工单标题','title')}{select(tool==='inspection'?'巡检类型':'维护类型','type',tool==='inspection'?['日常巡检','专项巡检','节假日巡检']:tool==='repair'?['故障维修','预防性维修']:['预防性','纠正性','预测性'])}{tool!=='inspection'&&deviceSelect}{text('计划时间','due','datetime-local')}{text('负责人 ID','owner')}{tool==='repair'&&select('优先级','priority',['紧急','重要','次要','提示'])}<label>{tool==='inspection'?'检查项清单':'任务说明'}<textarea aria-label={tool==='inspection'?'检查项清单':'任务说明'} value={values.items} onChange={e=>set('items',e.target.value)}/></label><p className="maintenance-boundary">{tool==='inspection'?'服务器支持新建标题、计划时间、负责人；类型、检查项与现有巡检的编辑仅可保存在本地补充草稿，不修改已下发任务。':'新建维护计划、工单扩展字段尚未接通，保存仅生成本地草稿。'}</p>{feedback}</div>
 const localList=d.records.filter(r=>(!type||r.type===type)&&(!query||Object.values(r).some(v=>v.includes(query)))&&(!status||status==='pending'))
 const today=new Date(),y=Number(month.slice(0,4)),m=Number(month.slice(5,7)),days=new Date(y,m,0).getDate(),offset=(new Date(y,m-1,1).getDay()+6)%7
 return <>
 {tool==='inspection'&&<><div className="maintenance-tools-filter"><button className="operations-button is-active" onClick={()=>{setEditingId('');setForm(true)}}>创建巡检任务</button>{filters}<button className="operations-button" aria-pressed={view==='list'} onClick={()=>setView('list')}>列表视图</button><button className="operations-button" aria-pressed={view==='map'} onClick={()=>setView('map')}>地图视图</button></div>
 <Surface title="巡检任务">{view==='list'?<DataTable headers={['任务编号','站点','巡检类型','巡检人','计划日期','开始时间','完成时间','检查项进度','异常数','状态','操作']} rows={filteredInspections.map(i=>[i.id,station.name,'未提供',i.owner||'—',i.dueAt,'—',i.completedAt||'—','—','—',INSPECTION_STATUS[i.status],<div className="operations-actions"><button className="operations-link" onClick={()=>setDetail({编号:i.id,标题:i.title,计划时间:i.dueAt,负责人:i.owner||'—',状态:INSPECTION_STATUS[i.status]})}>查看</button><button className="operations-link" onClick={()=>{setEditingId(i.id);setValues(v=>({...v,title:i.title,due:i.dueAt.replace(" ","T").slice(0,16),owner:i.owner||"",type:"日常巡检",items:""}));d.setDirty(false);d.setNotice("");setForm(true)}}>编辑</button></div>])}/>:<div className="maintenance-map-empty"><h3>站点巡检地图</h3><p>地图底图服务尚未接通；授权站点坐标如下。</p>{stations.map(s=><p key={s.id}>{s.name} · {s.lng&&s.lat?`${s.lng}, ${s.lat}`:'未提供经纬度'}</p>)}</div>}</Surface>
 <div className="maintenance-three"><Surface title="本月巡检完成率"><div className="maintenance-completion-ring" style={inspectionRate===null?undefined:{background:`conic-gradient(#1e6656 ${inspectionRate}%, #edf3f0 0)`}}><strong>{inspectionRate===null?"—":`${inspectionRate}%`}</strong></div><p>按已接入巡检的计划月份统计</p><p>已完成 {monthInspections.filter(i=>i.status==='completed').length} · 待执行 {monthInspections.filter(i=>i.status==='pending').length}</p></Surface><Surface title="异常发现趋势（每周）"><EmptyChart label="巡检异常趋势" axes="W1　W2　W3　W4"/></Surface><Surface title="站点巡检覆盖率">{stations.map(s=><div className="maintenance-unknown-bar" key={s.id}>{s.name}<span>—</span></div>)}<small>计划覆盖分母及检查项尚未接通</small></Surface></div></>}
 {tool==='plan'&&<><div className="maintenance-tools-filter"><button className="operations-button is-active" onClick={()=>setForm(true)}>创建维护计划</button>{filters}<button className="operations-button" aria-pressed={view!=='table'} onClick={()=>setView('list')}>月历视图</button><button className="operations-button" aria-pressed={view==='table'} onClick={()=>setView('table')}>列表视图</button></div>
 {view!=='table'&&<Surface title="维护月历" actions={<input type="month" aria-label="维护月份" value={month} onChange={e=>setMonth(e.target.value||new Date().toISOString().slice(0,7))}/>}><p className="maintenance-calendar-legend">预防性 · 纠正性 · 预测性　所有日历记录均为本地草稿</p><div className="maintenance-calendar">{['周一','周二','周三','周四','周五','周六','周日'].map(x=><b key={x}>{x}</b>)}{Array.from({length:Math.ceil((days+offset)/7)*7},(_,i)=>{const day=i-offset+1,date=`${month}-${String(day).padStart(2,'0')}`;return <div key={i} className={day<1||day>days?'is-outside':''}>{day>0&&day<=days&&<><span>{day}</span>{localList.filter(r=>r.due?.slice(0,10)===date).map(r=><button key={r.id} onClick={()=>setDetail(r)}>{r.title} · 本地</button>)}</>}</div>})}</div></Surface>}
 <Surface title={view==='table'?'维护计划列表':'未来 7 天待执行任务'}><DataTable headers={['计划编号','站点','维护类型','设备 / 系统','计划日期','负责人','状态','操作']} rows={localList.filter(r=>view==='table'||(Date.parse(r.due)>=Date.now()&&Date.parse(r.due)<=Date.now()+7*86400000)).map(r=>[r.id.slice(0,8),station.name,r.type,devices.find(x=>x.id===r.device)?.name||r.device,r.due,r.owner,'本地草稿 · 未执行',<button className="operations-link" onClick={()=>setDetail(r)}>查看</button>])} empty="维护计划服务未接通；当前筛选范围暂无本地计划草稿"/></Surface></>}
 {tool==='spares'&&<div className="maintenance-split"><div><div className="maintenance-four">{['备件总类','库存总量','低库存预警','本月消耗'].map(x=><Surface key={x} title={x}><strong className="maintenance-big">—</strong><small>库存服务未接通</small></Surface>)}</div><div className="maintenance-tools-filter"><input aria-label="搜索备件名称规格" placeholder="搜索备件名称、规格…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="备件类别" value={type} onChange={e=>setType(e.target.value)}>{['','PCS模块','BMS板卡','温控部件','电气元件','传感器','其他'].map(x=><option key={x} value={x}>{x||'类别：全部'}</option>)}</select><input aria-label="仓库筛选" placeholder="仓库"/><select aria-label="库存状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="">状态：全部</option><option>低库存</option><option>正常</option><option>缺货</option></select></div><Surface title="备件库存"><DataTable headers={['备件编号','备件名称','类别','规格型号','所在仓库','当前库存','安全库存','单位','最近入库','状态','操作']} rows={[]} empty="备件库存接口尚未接通；无法核验可用库存或进行出入库"/></Surface></div>
 <Surface title="快速出入库申请"><form className="maintenance-draft-form" onSubmit={e=>{e.preventDefault();save()}}>{select('操作类型','direction',['入库','出库'])}{text('备件名称 / 规格','part')}{text('申请数量','quantity','number')}<label>关联维修工单<select aria-label="关联维修工单" value={values.order} onChange={e=>set('order',e.target.value)}><option value="">无关联工单</option>{orders.map(o=><option key={o.id} value={o.id}>{o.id} · {o.title}</option>)}</select></label><label>经办备注<textarea value={values.note} onChange={e=>set('note',e.target.value)} maxLength={2000}/></label><p className="maintenance-boundary">库存、仓库与库存校验服务未接通；填写的备件仅为申请草稿，不会更改库存。</p>{feedback}<button className="operations-button is-active">检查并保存本地草稿</button></form></Surface></div>}
 {tool==='repair'&&<><div className="maintenance-tools-filter"><button className="operations-button is-active" onClick={()=>d.leave(()=>onOpenOrders?.(station.id))}>创建工单</button><button className="operations-button" onClick={()=>setForm(true)}>工单扩展草稿</button>{filters}<select aria-label="工单优先级" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">优先级：全部</option><option>紧急</option><option>重要</option><option>次要</option><option>提示</option></select>{priority&&<small>服务未提供优先级；未分类记录不匹配筛选。</small>}<button className="operations-button" aria-pressed={view==='list'} onClick={()=>setView('list')}>看板视图</button><button className="operations-button" aria-pressed={view==='table'} onClick={()=>setView('table')}>列表视图</button></div>
 {view==='table'?<Surface title="维修工单列表"><DataTable headers={['工单编号','站点 / 设备','内容','负责人','计划日期','状态','操作']} rows={filteredOrders.map(o=>[o.id,station.name,o.title,o.owner||'未分配',o.dueAt||'—',WORK_ORDER_STATUS[o.status],<button className="operations-link" onClick={()=>d.leave(()=>onOpenOrders?.(station.id,o.id))}>查看工单</button>])}/></Surface>:<div className="maintenance-kanban">{['待分配','已分配','维修中','待验收','已完成'].map((name,index)=>{const rows=filteredOrders.filter(o=>index===0?o.status==='pending'&&!o.owner:index===1?o.status==='pending'&&!!o.owner:index===2?o.status==='processing':index===4?o.status==='completed':false);return <section key={name}><h3>{name} <span>{index===3?'—':rows.length}</span></h3>{rows.map(o=><button className="maintenance-order-card" key={o.id} onClick={()=>d.leave(()=>onOpenOrders?.(station.id,o.id))}><b>{o.id}</b><small>{station.name}</small><strong>{o.title}</strong><p>{o.description||'未提供故障描述'}</p><footer>{o.owner||'未分配'}<span>{o.dueAt||'—'}</span></footer></button>)}{!rows.length&&<p className="maintenance-boundary">{index===3?'当前接口无验收状态':'暂无工单'}</p>}</section>})}</div>}
 <div className="maintenance-four">{['平均响应时间','平均修复时间','一次修复率','本月工单数'].map((x,i)=><Surface key={x} title={x}><strong className="maintenance-big">{i===3?orders.filter(o=>o.createdAt?.startsWith(today.toISOString().slice(0,7))).length:'—'}</strong><small>{i===3?'按已接入记录统计':'统计口径未接通'}</small></Surface>)}</div></>}
 {tool==='diagnostics'&&<div className="maintenance-diagnostics"><aside className="maintenance-device-tree"><label><img src="/figma/maintenance/search.svg" alt=""/><input aria-label="搜索诊断设备" value={query} placeholder="搜索场站或设备" onChange={e=>setQuery(e.target.value)}/></label><strong>{station.name}</strong>{devices.filter(x=>`${x.name} ${x.code}`.includes(query)).map(x=><button key={x.id} aria-pressed={deviceId===x.id} onClick={()=>d.leave(()=>{setDeviceId(x.id);setValues(v=>({...v,mode:'手动诊断',duration:'60',interval:'5',voltageMin:'',voltageMax:'',temperatureMax:'',socMin:'',socMax:'',note:''}));d.setDirty(false);setForm(false)})}>{x.name}<small>{x.code}</small></button>)}</aside><div><header className="maintenance-tools-filter"><h2>{device?.name||'选择已注册设备'}</h2><span>Model: {device?.model||'—'}</span><button className="operations-button" disabled={!device} onClick={()=>setForm(true)}>配置参数</button><button className="operations-button is-active" disabled={!device} onClick={()=>setForm(true)}>开始诊断</button></header><div className="maintenance-diagnostic-metrics">{[['输出电压','电压'],['有功功率','功率'],['IGBT平均温度','IGBT'],['SOC 荷电状态','SOC'],['单体最大温差','温差'],['极柱接触内阻','内阻']].map(([label,match])=><Surface key={label} title={label}><strong className="maintenance-big">{formatPoint(device?.points.find(p=>p.label.toLowerCase().includes(match.toLowerCase())))}</strong><small>Range: 未提供阈值</small></Surface>)}</div><Surface title="诊断记录"><DataTable headers={['诊断时间','诊断类型','结果状态','发现问题','建议措施','操作人']} rows={[]} empty="远程诊断服务未接通；暂无实际诊断结果"/></Surface></div></div>}
 {tool==='health'&&<HealthAnalysis station={station} stations={stations} onHealthDevice={onHealthDevice}/>}
 {tool!=='spares'&&feedback}
 {['spares','plan','inspection','repair','diagnostics'].includes(tool)&&<DraftRecords records={d.records}/>}
 {form&&<Modal title={tool==='inspection'?(editingId?'编辑巡检本地补充':'创建巡检任务'):tool==='plan'?'创建维护计划':tool==='repair'?'创建工单草稿':'远程诊断配置'} onClose={()=>d.leave(()=>setForm(false))} actions={<><button className="operations-button" disabled={busy} onClick={()=>d.leave(()=>setForm(false))}>取消</button>{tool==='inspection'&&!editingId&&<button className="operations-button" disabled={busy||DEMO_MODE} onClick={createInspection}>{busy?'正在创建…':'创建服务器巡检'}</button>}<button className="operations-button is-active" disabled={busy} onClick={save}>保存本地草稿</button></>}>
 {tool==='diagnostics'?<div className="maintenance-draft-form maintenance-diagnostic-form"><p>{device?.name} · {device?.code}</p>{select('诊断类型','mode',['手动诊断','AI诊断','自动诊断'])}{text('诊断时长（秒）','duration','number')}{text('采样间隔（秒）','interval','number')}{text('电压下限 V','voltageMin','number')}{text('电压上限 V','voltageMax','number')}{text('温度上限 °C','temperatureMax','number')}{text('SOC 下限 %','socMin','number')}{text('SOC 上限 %','socMax','number')}<label>诊断说明<textarea value={values.note} onChange={e=>set('note',e.target.value)}/></label><p className="maintenance-boundary">诊断服务与参数写入未接通；保存配置只创建本地草稿，不会执行设备指令。</p>{feedback}</div>:commonForm}</Modal>}
 {detail&&<Modal title="运维记录详情" onClose={()=>setDetail(null)} actions={<button className="operations-button" onClick={()=>setDetail(null)}>关闭</button>}><dl className="maintenance-record-detail">{Object.entries(detail).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl></Modal>}{d.dialog}
 </>
}
function HealthAnalysis({station,stations,onHealthDevice}:{station:Station,stations:Station[],onHealthDevice?:(stationId:string,deviceId:string)=>void}){
 const [windowDays,setWindowDays]=useState('30'),[category,setCategory]=useState(''),[rating,setRating]=useState('')
 const devices=(station.deviceInventory||[]).filter(x=>!category||`${x.group} ${x.code}`.toLowerCase().includes(category.toLowerCase()))
 return <><div className="maintenance-tools-filter"><select aria-label="健康分析设备类型" value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部设备类型</option>{['PCS','BMS','电池','HVAC'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="健康观察窗" value={windowDays} onChange={e=>setWindowDays(e.target.value)}>{['7','30','90'].map(x=><option key={x} value={x}>近 {x} 天</option>)}</select><select aria-label="健康等级" value={rating} onChange={e=>setRating(e.target.value)}><option value="">健康等级：全部</option><option>需诊断</option><option>需关注</option><option>良好</option></select><button className="operations-button" onClick={()=>exportOperationsCsv('设备健康清单.csv',['设备','站点','通信','健康度','观察窗'],devices.map(x=>[x.code,station.name,x.status,'未接通',windowDays]))}>导出健康清单</button></div><div className="maintenance-four">{['设备总数','健康设备','告警设备','故障设备'].map((x,i)=><Surface title={x} key={x}><strong className="maintenance-big">{i===0?devices.length:'—'}</strong><small>{i===0?'已注册设备':'健康分类未接通'}</small></Surface>)}</div>
 <div className="maintenance-two"><Surface title="各子系统健康指标"><div className="maintenance-health-summary"><strong>—<small>健康评分</small></strong><div>{['PCS 储能变流系统','BMS 电池管理系统','温控系统','消防安全系统','电气及网柜'].map(x=><div className="maintenance-unknown-bar" key={x}>{x}<span>—</span></div>)}</div></div><p className="maintenance-boundary">健康评分与风险因子接口尚未接通，不根据设备在线状态推算分数。</p></Surface><Surface title="场站设备类型健康热力分布"><DataTable headers={['场站群组','PCS','BMS','温控','消防','电气']} rows={stations.map(s=>[s.name,'—','—','—','—','—'])}/></Surface><Surface title={`近期健康趋势（${windowDays}天）`}><EmptyChart label="健康趋势" axes={`最近 ${windowDays} 天 · 评分`} /></Surface><Surface title="高风险设备 Top 5"><DataTable headers={['排名','设备名','所属站点','健康度','风险系数']} rows={[]} empty="设备风险评分未接通，无法进行真实排名"/></Surface></div>
 <div className="maintenance-split"><Surface title="设备健康排行"><DataTable headers={['设备 / 站点','健康度','30天趋势','重复故障','最近维护','动作']} rows={(rating?[]:devices).map(x=>[`${x.code} / ${station.name}`,'—','—','—','—',<button className="operations-link" onClick={()=>onHealthDevice?.(station.id,x.id)}>查看档案</button>])}/></Surface><Surface title="风险构成">{['效率偏差','直流母线波动','散热性能','通讯质量'].map(x=><div className="maintenance-unknown-bar" key={x}>{x}<span>—</span></div>)}<p className="maintenance-boundary">风险因子、基线与诊断建议尚未接通</p></Surface></div><div className="maintenance-two"><Surface title="重复故障模式"><DataTable headers={['模式','影响设备','30天','最近发生','建议']} rows={[]} empty="故障聚合、复发次数与建议尚未接通"/></Surface><Surface title="健康履历"><EmptyChart label="维护与评分变化"/></Surface></div></>
}
