const {test}=require('node:test'); const assert=require('node:assert/strict'); const {chromium}=require('playwright');
async function setup(t){
 const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(5000);await page.addInitScript(()=>sessionStorage.setItem('enerlution-api-token','task7'));
 const requests=[];let failed=true;await page.route('http://127.0.0.1:18090/api/**',async r=>{const q=r.request(),path=new URL(q.url()).pathname.slice(4);requests.push({path,method:q.method(),body:q.postDataJSON()});let data=[],status=200,msg='ok';
 if(path==='/auth/me')data={id:'7',name:'管理员',account:'manager',role:'integrator',organization:'华东',stationIds:[],permissions:['customer.read','customer.manage','organization.member.read','organization.manage','role.manage','member.grant.manage','audit.read']};
 else if(path==='/platform/customers')data=[{id:3,name:'真实客户',station_count:1,can_edit:true,stations:[{id:1,name:'真实站点',code:'S1'}]}];
 else if(path==='/platform/customers/3'){if(failed){failed=false;status=409;msg='客户并发冲突'}else data=null}
 else if(path==='/audit')data=[{id:8,actor_id:7,action:'role.update',occurred_at:'2026-09-26T08:00:00Z',detail:'role=3'}];
 await r.fulfill({status,contentType:'application/json',body:JSON.stringify({code:status===200?0:status,msg,data})})});
 await page.goto(process.env.API_PREVIEW_URL||'http://127.0.0.1:8461',{waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('button',{name:'平台管理',exact:true}).click();return {page,requests};
}
test('customer failure preserves input and global navigation can cancel or discard',async t=>{const {page,requests}=await setup(t);await page.getByRole('button',{name:'查看详情',exact:true}).click();await page.getByRole('button',{name:'返回客户列表'}).waitFor();await page.getByRole('button',{name:'编辑客户资料'}).click();await page.getByLabel('客户名称 *',{exact:true}).fill('修改客户');await page.getByLabel('服务联系人（本地草稿）',{exact:true}).fill('保留联系人');await page.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('alert').filter({hasText:'客户并发冲突'}).waitFor();assert.equal(await page.getByLabel('客户名称 *',{exact:true}).inputValue(),'修改客户');assert.equal(await page.getByLabel('服务联系人（本地草稿）',{exact:true}).inputValue(),'保留联系人');await page.getByRole('button',{name:'设置',exact:true}).dispatchEvent('click');await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await page.getByLabel('客户名称 *',{exact:true}).inputValue(),'修改客户');assert.equal(await page.getByLabel('服务联系人（本地草稿）',{exact:true}).inputValue(),'保留联系人');await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByRole('button',{name:'编辑客户资料'}).click();assert.equal(await page.getByLabel('客户名称 *',{exact:true}).inputValue(),'真实客户');assert.equal(await page.getByLabel('服务联系人（本地草稿）',{exact:true}).inputValue(),'');assert.equal(requests.filter(r=>r.method==='PUT').length,1)});
test('configuration drafts reopen and discard restore without server writes',async t=>{const {page,requests}=await setup(t);await page.getByRole('button',{name:'配置中心',exact:true}).click();await page.getByRole('tab',{name:'审批规则',exact:true}).click();await page.getByRole('button',{name:'新建规则',exact:true}).click();await page.getByLabel('规则名称',{exact:true}).fill('本地审批草稿');await page.getByRole('button',{name:'保存本地草稿',exact:true}).click();await page.getByRole('tab',{name:'系统配置',exact:true}).click();await page.getByRole('tab',{name:'审批规则',exact:true}).click();await page.getByRole('button',{name:'编辑草稿',exact:true}).click();assert.equal(await page.getByLabel('规则名称',{exact:true}).inputValue(),'本地审批草稿');await page.getByLabel('规则名称',{exact:true}).fill('未保存名称');await page.getByRole('tab',{name:'接口接入',exact:true}).click();await page.getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByRole('tab',{name:'审批规则',exact:true}).click();await page.getByRole('button',{name:'编辑草稿',exact:true}).click();assert.equal(await page.getByLabel('规则名称',{exact:true}).inputValue(),'本地审批草稿');assert.equal(requests.filter(r=>['POST','PUT','DELETE'].includes(r.method)).length,0)});
test('audit detail and result filters preserve unknown execution semantics',async t=>{const {page}=await setup(t);await page.getByRole('button',{name:'安全审计',exact:true}).click();await page.getByText('仅显示当前账号的审计事件。',{exact:true}).waitFor();await page.getByRole('button',{name:'查看详情',exact:true}).click();await page.getByRole('heading',{name:'操作记录',exact:true}).waitFor();await page.getByText('未提供',{exact:true}).first().waitFor();await page.getByRole('button',{name:'返回审计列表'}).click();await page.getByLabel('审计结果').selectOption('拒绝');await page.getByText('没有符合筛选条件的审计记录').waitFor();});

test('demo role drafts survive cancel and discard before navigating to configuration',async t=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});t.after(()=>browser.close());const page=await browser.newPage();page.setDefaultTimeout(7000);await page.goto(process.env.DEMO_PREVIEW_URL||'http://127.0.0.1:8460',{waitUntil:'domcontentloaded',timeout:60000});await page.getByLabel('登录账号',{exact:true}).fill('integrator@enerlution.cn');await page.getByLabel('密码',{exact:true}).fill('Demo@2026');await page.getByRole('button',{name:'登录',exact:true}).click();await page.getByLabel('动态验证码',{exact:true}).fill('246810');await page.getByRole('button',{name:'完成验证',exact:true}).click();await page.getByRole('button',{name:'平台管理',exact:true}).click();if(await page.getByRole('button',{name:'组织权限',exact:true}).count())await page.getByRole('button',{name:'组织权限',exact:true}).click();await page.getByRole('tab',{name:'角色权限',exact:true}).click();const checkbox=page.getByRole('checkbox',{name:'新建站点',exact:true});await checkbox.check();await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await checkbox.isChecked(),true);await page.getByRole('button',{name:'配置中心',exact:true}).click();await page.getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByRole('tab',{name:'审批规则',exact:true}).waitFor();await page.getByRole('button',{name:'组织权限',exact:true}).click();await page.getByRole('tab',{name:'角色权限',exact:true}).click();assert.equal(await page.getByRole('checkbox',{name:'新建站点',exact:true}).isChecked(),false)
});
test('integration credentials remain ephemeral and account scoped drafts do not cross users',async t=>{const {page,requests}=await setup(t);await page.getByRole('button',{name:'配置中心',exact:true}).click();await page.getByRole('tab',{name:'接口接入',exact:true}).click();await page.getByRole('button',{name:'申请API凭证 / 配置集成',exact:true}).click();await page.getByLabel('凭证名称',{exact:true}).fill('测试凭证申请');await page.getByLabel('接口地址',{exact:true}).fill('https://example.test/hook?secret=should-not-persist');await page.getByLabel('认证凭证（仅本次输入）',{exact:true}).fill('secret-not-persisted');await page.getByRole('button',{name:'保存本地草稿',exact:true}).click();const storage=await page.evaluate(()=>JSON.stringify({...localStorage}));assert(!storage.includes('should-not-persist'));assert(!storage.includes('secret-not-persisted'));await page.getByRole('button',{name:'编辑草稿',exact:true}).click();assert.equal(await page.getByLabel('认证凭证（仅本次输入）',{exact:true}).inputValue(),'');await page.route('http://127.0.0.1:18090/api/auth/me',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({code:0,data:{id:'88',name:'另一管理员',account:'other',role:'integrator',stationIds:[],permissions:['role.manage','organization.manage']}})}));await page.reload({waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('button',{name:'平台管理',exact:true}).click();await page.getByRole('button',{name:'配置中心',exact:true}).click();await page.getByRole('tab',{name:'接口接入',exact:true}).click();assert.equal(await page.getByText('测试凭证申请',{exact:true}).count(),0);assert.equal(requests.filter(r=>['POST','PUT','DELETE'].includes(r.method)).length,0)});

test('customer entitlement drafts validate dates, reopen and never change server quotas',async t=>{const {page,requests}=await setup(t);await page.getByRole('button',{name:'查看详情',exact:true}).click();await page.getByRole('button',{name:'编辑权益',exact:true}).click();await page.getByLabel('合同编号',{exact:true}).fill('LOCAL-001');await page.getByLabel('服务开始日期',{exact:true}).fill('2026-10-01');await page.getByLabel('服务结束日期',{exact:true}).fill('2026-09-01');await page.getByRole('button',{name:'保存本地草稿',exact:true}).click();await page.getByRole('alert').filter({hasText:'服务结束日期不能早于开始日期'}).waitFor();await page.getByLabel('服务结束日期',{exact:true}).fill('2027-10-01');await page.getByRole('button',{name:'保存本地草稿',exact:true}).click();await page.getByRole('button',{name:'编辑权益',exact:true}).click();assert.equal(await page.getByLabel('合同编号',{exact:true}).inputValue(),'LOCAL-001');await page.getByLabel('站点配额',{exact:true}).fill('8');await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'放弃修改',exact:true}).click();await page.getByRole('button',{name:'编辑权益',exact:true}).click();assert.equal(await page.getByLabel('站点配额',{exact:true}).inputValue(),'');assert.equal(requests.filter(r=>['POST','PUT','DELETE'].includes(r.method)).length,0)});

test('temporary grants use server terms and omit permanent or restricted rows',async t=>{const {page,requests}=await setup(t);const member={id:41,display_name:'期限成员',account:'term.member',organization_id:1,management_organization_id:1,enabled:true};await page.route('http://127.0.0.1:18090/api/members*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({code:0,data:[member]})}));const grant={id:3,roleId:7,roleName:'真实期限角色',stationIds:[1],stations:[{id:1,name:'服务器站点'}],validFrom:'2026-09-01T00:00:00Z',validUntil:'2026-10-01T00:00:00Z',term:'30d',status:'active',scopeRestricted:false,rolePermissions:[{code:'station.read',name:'真实读取权限'}]};await page.route('http://127.0.0.1:18090/api/members/41/grants',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({code:0,data:[grant,{...grant,id:4,roleName:'长期行',term:'permanent',validUntil:null},{...grant,id:5,roleName:'受限行',scopeRestricted:true},{...grant,id:6,roleName:'过期角色',status:'expired'}]})}));await page.getByRole('button',{name:'组织权限',exact:true}).click();await page.getByRole('tab',{name:'临时授权',exact:true}).click();await page.getByRole('cell',{name:'真实期限角色',exact:true}).waitFor();assert.equal(await page.getByRole('cell',{name:'长期行',exact:true}).count(),0);assert.equal(await page.getByRole('cell',{name:'受限行',exact:true}).count(),0);await page.getByLabel('授权状态',{exact:true}).selectOption('expired');await page.getByRole('cell',{name:'过期角色',exact:true}).waitFor();assert.equal(await page.getByRole('cell',{name:'真实期限角色',exact:true}).count(),0);await page.getByRole('button',{name:'查看',exact:true}).click();await page.getByText('真实读取权限',{exact:true}).waitFor();await page.getByText('授权原因',{exact:true}).waitFor();assert.equal(requests.filter(r=>['POST','PUT','DELETE'].includes(r.method)).length,0)});

test('notification channel changes guard unsaved form and preserve inputs on cancellation',async t=>{const {page}=await setup(t);await page.getByRole('button',{name:'配置中心',exact:true}).click();await page.getByRole('tab',{name:'告警与通知',exact:true}).click();await page.getByRole('button',{name:'添加判定规则',exact:true}).click();await page.getByLabel('规则名称',{exact:true}).fill('尚未保存的通知');await page.getByRole('button',{name:'配置草稿',exact:true}).first().click();await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await page.getByLabel('规则名称',{exact:true}).inputValue(),'尚未保存的通知');await page.getByRole('button',{name:'配置草稿',exact:true}).first().click();await page.getByRole('button',{name:'放弃修改',exact:true}).click();assert.equal(await page.getByLabel('规则名称',{exact:true}).inputValue(),'');assert.equal(await page.getByLabel('下发通道',{exact:true}).inputValue(),'SMS')});
for(const field of ['服务联系人（本地草稿）','客户主体（本地草稿）'])test(`fixround1 customer keyboard stays in ${field}`,async t=>{
 const {page,requests}=await setup(t);await page.getByRole('button',{name:'查看详情',exact:true}).click();await page.getByRole('button',{name:'编辑客户资料',exact:true}).click();const input=page.getByLabel(field,{exact:true});await input.focus();await page.keyboard.type('ABC',{delay:100});assert.equal(await input.inputValue(),'ABC');assert.equal(await page.getByLabel('客户名称 *',{exact:true}).inputValue(),'真实客户');assert.equal(await input.evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await input.inputValue(),'ABC');assert.equal(await input.evaluate(e=>e===document.activeElement),true);assert.equal(requests.filter(r=>r.method==='PUT').length,0)
});
test('fixround1 entitlement keyboard stays in service plan',async t=>{const {page}=await setup(t);await page.getByRole('button',{name:'查看详情',exact:true}).click();await page.getByRole('button',{name:'编辑权益',exact:true}).click();const input=page.getByLabel('服务套餐',{exact:true});await input.focus();await page.keyboard.type('ABC',{delay:100});assert.equal(await input.inputValue(),'ABC');assert.equal(await page.getByLabel('合同编号',{exact:true}).inputValue(),'');assert.equal(await input.evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');await page.getByRole('button',{name:'继续编辑',exact:true}).click();assert.equal(await input.inputValue(),'ABC')});
for(const [tab,field] of [['安全策略','登录失败次数'],['系统配置','数据保留期（天）']])test(`fixround1 singleton ${tab} reopens and survives tab switch and reload`,async t=>{
 const {page,requests}=await setup(t);await page.getByRole('button',{name:'配置中心',exact:true}).click();await page.getByRole('tab',{name:tab,exact:true}).click();await page.getByLabel(field,{exact:true}).fill('3');await page.getByRole('button',{name:'保存本地草稿',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'编辑配置草稿',exact:true}).click();assert.equal(await page.getByLabel(field,{exact:true}).inputValue(),'3');await page.getByLabel(field,{exact:true}).fill('5');await page.getByRole('button',{name:'保存本地草稿',exact:true}).click();await page.getByRole('tab',{name:'审批规则',exact:true}).click();await page.getByRole('tab',{name:tab,exact:true}).click();assert.equal(await page.getByLabel(field,{exact:true}).inputValue(),'5');await page.reload({waitUntil:'domcontentloaded',timeout:60000});await page.getByRole('button',{name:'平台管理',exact:true}).click();await page.getByRole('button',{name:'配置中心',exact:true}).click();await page.getByRole('tab',{name:tab,exact:true}).click();assert.equal(await page.getByLabel(field,{exact:true}).inputValue(),'5');const rows=await page.evaluate(()=>JSON.parse(localStorage.getItem('enerlution:platform-config:api:7')));assert.equal(rows.filter(r=>r.tab===tab).length,1);assert.equal(rows.find(r=>r.tab===tab).id,tab);assert.equal(requests.filter(r=>['POST','PUT','DELETE'].includes(r.method)).length,0)
});
test('fixround1 legacy duplicate singleton drafts retain last saved values within their account and mode',async t=>{const {page}=await setup(t);await page.evaluate(()=>{const tabs=['安全策略','系统配置'];const rows=tabs.flatMap(tab=>[{id:tab,tab,name:tab,values:{[tab==='安全策略'?'登录失败次数':'数据保留期（天）']:'3'}},{id:'old-'+tab,tab,name:tab,values:{[tab==='安全策略'?'登录失败次数':'数据保留期（天）']:'5'}}]);localStorage.setItem('enerlution:platform-config:api:7',JSON.stringify(rows));localStorage.setItem('enerlution:platform-config:demo:7','mode-sentinel');localStorage.setItem('enerlution:platform-config:api:88','account-sentinel')});await page.getByRole('button',{name:'配置中心',exact:true}).click();for(const [tab,field] of [['安全策略','登录失败次数'],['系统配置','数据保留期（天）']]){await page.getByRole('tab',{name:tab,exact:true}).click();assert.equal(await page.getByLabel(field,{exact:true}).inputValue(),'5')}const data=await page.evaluate(()=>({rows:JSON.parse(localStorage.getItem('enerlution:platform-config:api:7')),mode:localStorage.getItem('enerlution:platform-config:demo:7'),account:localStorage.getItem('enerlution:platform-config:api:88')}));assert.equal(data.rows.length,2);assert.equal(data.mode,'mode-sentinel');assert.equal(data.account,'account-sentinel')});
