const { test } = require('node:test')
const assert = require('node:assert/strict')
const { chromium } = require('playwright')

test('dirty strategy editor guards primary navigation and validates save before leaving', async t => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  t.after(() => browser.close())
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
  await context.addInitScript(() => sessionStorage.setItem('enerlution-api-token', 'strategy-guard-test'))
  const page = await context.newPage()
  page.setDefaultTimeout(12000)
  const grants = ['asset.read', 'strategy.read', 'strategy.manage']
  const user = { id: 'strategy-guard-user', name: 'Strategy', account: 'strategy@test', role: 'integrator', organization: 'Test', stationIds: ['12'], permissions: grants, stationPermissions: { 12: grants }, organizationPermissions: {} }
  await page.route('http://127.0.0.1:18090/api/**', async route => {
    const path = new URL(route.request().url()).pathname.slice(4)
    const data = path === '/auth/me' ? user : path === '/stations' ? [{ id: 12, name: '策略站点', code: 'S-12', rated_power_kw: 100, capacity_kwh: 200 }] : []
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ code: 0, data }) })
  })
  await page.goto(process.env.STATIONS_API_URL || process.env.API_PREVIEW_URL || 'http://127.0.0.1:8451', { waitUntil: 'domcontentloaded', timeout: 60000 })
  await page.getByRole('button', { name: '资产与站点', exact: true }).click()
  await page.locator('.station-name-button').first().click()
  await page.getByRole('navigation', { name: '站点二级导航' }).getByRole('button', { name: '策略运行' }).click()
  await page.getByRole('button', { name: '新增策略方案' }).click()
  await page.getByLabel('方案名称', { exact: true }).fill('守卫方案')
  await page.getByRole('button', { name: '创建并配置' }).click()
  await page.getByLabel('策略名称').fill('')
  await page.getByRole('button', { name: '总览', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '未保存的策略' })
  await dialog.waitFor()
  await dialog.getByRole('button', { name: '继续编辑' }).click()
  assert.equal(await page.getByLabel('策略名称').inputValue(), '')
  await page.getByRole('button', { name: '总览', exact: true }).click()
  await dialog.getByRole('button', { name: '保存并离开' }).click()
  await page.getByRole('alert').filter({ hasText: '名称' }).waitFor()
  assert.equal(await page.locator('.strategy-editing').count(), 1)
  await page.getByLabel('策略名称').fill('守卫方案已保存')
  await dialog.getByRole('button', { name: '保存并离开' }).click()
  await page.locator('.strategy-editing').waitFor({ state: 'detached' })
  await page.getByRole('button', { name: '资产与站点', exact: true }).click()
  await page.getByRole('button', { name: '编辑守卫方案已保存' }).click()
  assert.equal(await page.getByLabel('策略名称').inputValue(), '守卫方案已保存')
})
