const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs')
const {chromium}=require('playwright')

test('Figma tariff calendar, templates and actual server periods remain distinct',async t=>{
  const browser=await chromium.launch({channel:'msedge',headless:true})
  t.after(()=>browser.close())
  const context=await browser.newContext({viewport:{width:1440,height:1000}})
  await context.addInitScript(()=>sessionStorage.setItem('enerlution-api-token','tariff-test'))
  const page=await context.newPage()
  page.setDefaultTimeout(12000)
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  const user={id:'7',name:'电价管理员',account:'tariff@test',role:'integrator',organization:'测试',stationIds:['12'],permissions:['asset.read','tariff.manage'],stationPermissions:{12:['asset.read','tariff.manage']},organizationPermissions:{}}
  const versions=[];const posts=[]
  await page.route('http://127.0.0.1:18090/api/**',async route=>{
    const request=route.request(),path=new URL(request.url()).pathname.slice(4)
    let data=[]
    if(path==='/auth/me')data=user
    else if(path==='/stations')data=[{id:12,name:'电价站点',code:'T-12',rated_power_kw:100,capacity_kwh:200}]
    else if(path==='/stations/12/tariffs')data=versions
    else if(path==='/tariffs'&&request.method()==='POST'){
      const body=request.postDataJSON();posts.push(body)
      versions.push({id:101,name:body.name,currency:body.currency,valid_from:body.validFrom,valid_until:body.validUntil,periods:body.periods.map(p=>({start_minute:p.startMinute,end_minute:p.endMinute,band:p.band,price_per_kwh:p.pricePerKwh}))})
      data={id:101}
    }
    await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({code:0,data})})
  })
  await page.goto(process.env.STATIONS_API_URL||process.env.API_PREVIEW_URL||process.env.PREVIEW_URL||'http://127.0.0.1:8451',{waitUntil:'domcontentloaded',timeout:45000})
  await page.getByRole('button',{name:'资产与站点',exact:true}).click()
  await page.locator('.station-name-button').first().click()
  await page.getByRole('button',{name:'电价设置',exact:true}).click()
  await page.getByRole('heading',{name:'电价日历'}).waitFor()
  fs.mkdirSync('test-results/figma-tariff',{recursive:true})
  await page.screenshot({path:'test-results/figma-tariff/calendar.png'})
  await page.getByRole('button',{name:'日模板管理',exact:true}).click()
  await page.getByRole('button',{name:'＋ 新增模板',exact:true}).click()
  await page.getByLabel('模板名称',{exact:true}).fill('测试工作日')
  await page.getByLabel('购电固定价',{exact:true}).fill('-0.1')
  await page.getByLabel('售电固定价',{exact:true}).fill('0.41')
  await page.screenshot({path:'test-results/figma-tariff/fixed.png'})
  await page.getByRole('button',{name:'保存模板',exact:true}).click()
  await page.getByRole('status').filter({hasText:'本机'}).waitFor()
  assert.equal(posts.length,0)
  await page.getByRole('button',{name:'创建生效期间',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'创建服务器电价生效期间'})
  await dialog.getByLabel('电价生效日期').fill('2030-01-01')
  await dialog.getByLabel('电价结束日期').fill('2031-01-01')
  await dialog.getByRole('button',{name:'创建新生效期间'}).click()
  await page.getByRole('status').filter({hasText:'已由服务器创建'}).waitFor()
  assert.equal(posts.length,1)
  assert.deepEqual(posts[0].periods,[{startMinute:0,endMinute:1440,band:'flat',pricePerKwh:-0.1}])
  await page.getByRole('button',{name:'创建生效期间',exact:true}).click()
  await dialog.getByRole('button',{name:'创建新生效期间'}).click()
  await dialog.getByRole('alert').filter({hasText:'重叠'}).waitFor()
  assert.equal(posts.length,1)
  await dialog.getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('button',{name:'编辑测试工作日',exact:true}).click()
  await page.getByRole('button',{name:'分时',exact:true}).click()
  await page.getByLabel('时段1结束时间').fill('08:00')
  await page.getByRole('button',{name:'新增电价时段',exact:true}).click()
  await page.getByLabel('时段2电价').fill('0.65')
  await page.screenshot({path:'test-results/figma-tariff/tou.png'})
  await page.getByRole('button',{name:'保存模板',exact:true}).click()
  await page.getByRole('heading',{name:'日模板管理'}).waitFor()
  await page.getByRole('button',{name:'编辑测试工作日',exact:true}).click()
  await page.getByRole('button',{name:'动态',exact:true}).click()
  await page.getByLabel('动态电价请求地址').fill('https://prices.example.test/tariff')
  await page.getByRole('button',{name:'测试连接',exact:true}).click()
  await page.getByRole('status').filter({hasText:'未接通'}).waitFor()
  await page.screenshot({path:'test-results/figma-tariff/dynamic.png'})
  await page.getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('dialog',{name:'未保存的模板'}).getByRole('button',{name:'不保存离开'}).click()
  await page.getByRole('button',{name:'返回日历',exact:true}).click()
  await page.getByRole('button',{name:'下个月',exact:true}).click()
  const assignment=page.locator('.tariff-day[data-current="true"] select:not(:disabled)').first()
  await assignment.selectOption({label:'测试工作日'})
  await page.getByRole('button',{name:'保存设置',exact:true}).click()
  assert.equal(posts.length,1)
  for(const width of [1366,1920]){
    await page.setViewportSize({width,height:1000})
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  }
  await page.getByRole('button',{name:'日模板管理',exact:true}).click()
  await page.getByRole('button',{name:'删除测试工作日',exact:true}).click()
  await page.getByRole('dialog',{name:'删除日模板'}).getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('button',{name:'删除测试工作日',exact:true}).click()
  await page.getByRole('dialog',{name:'删除日模板'}).getByRole('button',{name:'确认删除',exact:true}).click()
  assert.equal(await page.getByRole('button',{name:'编辑测试工作日',exact:true}).count(),0)
  assert.equal(posts.length,1)
  assert.deepEqual(errors,[])
})
