// Offline generator. Never opens a database or an MQTT connection.
const fs = require('node:fs');
const path = require('node:path');
const {DEFAULTS, loadProfile, validateDeployment, auditSources, FullPointScenario} = require('./profile.cjs');
const sqlText = text=>text===null?'NULL':"'"+String(text).replace(/'/g,"''")+"'";
const ROLES = [
  ['ems',57,null,1], ['emu',null,'SIM-EMU-01',null], ['bms',5,'SIM-BMS-01',2],
  ['pcs',4,'SIM-PCS-02',null], ['dcdc',13,'SIM-DCDC-01',null],
  ['tms',11,'SIM-HVAC-01',null], ['meter',8,'SIM-MTR-01',null],
];
const FIXED = new Map([['cabinet:20018',19],['cabinet:20021',21],['cabinet:20023',22],
  ...[90002,90003,90004,90005,90006,90007].map((id,i)=>[`ems:${id}`,441+i])]);
const roleOf = definition=>definition.namespace==='ems'?'ems':({pvdc:'dcdc',grid:'meter'}[definition.subsystem]||definition.subsystem);

function buildSeedSql(options={}) {
  const config=validateDeployment(options);
  const profile=loadProfile();
  const definitions=profile.catalog.definitions.filter(d=>d.namespace==='ems'||d.namespace==='config'||d.namespace==='cabinet'&&d.sourceType);
  const rows=definitions.map(d=>`(${sqlText(d.namespace)},${d.sourcePointId},${sqlText(d.namespace==='config'?null:roleOf(d))},${sqlText(d.wireType.toLowerCase())},${sqlText(d.verifiedUnit)},${sqlText(d.sourceName||`${d.namespace} ${d.sourcePointId}`)},${FIXED.get(`${d.namespace}:${d.sourcePointId}`)||'NULL'})`).join(',\n');
  const roles=ROLES.map(([role,id,code,binding])=>`(${sqlText(role)},${id||'NULL'},${sqlText(code)},${binding||'NULL'})`).join(',\n');
  return `-- Generated by scripts/ems-simulator/prepare.cjs. Synthetic binding metadata only.
-- Catalog ${profile.catalog.version}; source hash ${profile.catalog.sourceHash}.
-- Only ems_cloud_v2_proto. No telemetry/config facts, credentials or historical updates.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
DO $identity$
BEGIN
  IF current_database() <> 'ems_cloud_v2_proto' THEN
    RAISE EXCEPTION 'Refusing non-protocol database';
  END IF;
END $identity$;
SELECT pg_advisory_xact_lock(hashtextextended('${config.emsId}'::text,78291029));
CREATE TEMP TABLE sim_identity(ems_uuid uuid PRIMARY KEY,station_id bigint,period_id bigint,gateway_device_id bigint) ON COMMIT DROP;
INSERT INTO sim_identity VALUES('${config.emsId}',${config.stationId},${config.bindingPeriodId},${config.gatewayDeviceId});
CREATE TEMP TABLE sim_role(role text PRIMARY KEY,device_id bigint,device_code text,existing_binding_id bigint) ON COMMIT DROP;
INSERT INTO sim_role VALUES
${roles};
CREATE TEMP TABLE sim_definition(namespace text,source_id bigint,role text,value_type text,unit text,source_name text,fixed_point_id bigint,PRIMARY KEY(namespace,source_id)) ON COMMIT DROP;
INSERT INTO sim_definition VALUES
${rows};
DO $seed$
DECLARE
  identity_record record;
  role_record record;
  item record;
  definition_record record;
  mapping_record record;
  kind_record record;
  point_record record;
  binding_id bigint;
  model_id_value bigint;
  target_point_id bigint;
  chosen_kind text;
  generated_kind text;
  generated_code text;
  n integer;
BEGIN
  SELECT * INTO STRICT identity_record FROM sim_identity;
  PERFORM 1 FROM ems_gateway g JOIN device d ON d.id=g.device_id JOIN ems_binding_period p ON p.ems_uuid=g.ems_uuid
    WHERE g.ems_uuid=identity_record.ems_uuid AND g.device_id=identity_record.gateway_device_id
      AND d.station_id=identity_record.station_id AND p.id=identity_record.period_id AND p.station_id=d.station_id
      AND p.valid_from<=clock_timestamp() AND p.valid_to IS NULL FOR UPDATE OF g,d,p;
  IF NOT FOUND THEN RAISE EXCEPTION 'EMS/station/period/gateway identity mismatch'; END IF;

  -- Require existing non-test-EMU assets to match the approved identifiers.
  FOR role_record IN SELECT * FROM sim_role WHERE device_id IS NOT NULL LOOP
    PERFORM 1 FROM device d WHERE d.id=role_record.device_id AND d.station_id=identity_record.station_id
      AND (role_record.device_code IS NULL OR d.code=role_record.device_code) FOR UPDATE OF d;
    IF NOT FOUND THEN RAISE EXCEPTION 'Role asset mismatch: %',role_record.role; END IF;
  END LOOP;
  INSERT INTO device_model(manufacturer,name,category) VALUES('[模拟] EMS 协议测试','EMU v1 fixture','OTHER')
    ON CONFLICT(manufacturer,name) DO NOTHING;
  SELECT id INTO STRICT model_id_value FROM device_model WHERE manufacturer='[模拟] EMS 协议测试' AND name='EMU v1 fixture' AND category='OTHER';
  INSERT INTO device(station_id,model_id,code,name,serial_number)
    VALUES(identity_record.station_id,model_id_value,'SIM-EMU-01','[模拟]机柜控制器 EMU-01',NULL)
    ON CONFLICT(station_id,code) DO NOTHING;
  UPDATE sim_role SET device_id=(SELECT id FROM device WHERE station_id=identity_record.station_id AND code='SIM-EMU-01' AND model_id=model_id_value) WHERE role='emu';
  IF EXISTS(SELECT 1 FROM sim_role WHERE device_id IS NULL) THEN RAISE EXCEPTION 'Synthetic EMU identity mismatch'; END IF;

  FOR role_record IN SELECT * FROM sim_role LOOP
    SELECT count(*),min(id) INTO n,binding_id FROM device_binding
      WHERE binding_period_id=identity_record.period_id AND scope=CASE WHEN role_record.role='ems' THEN 'ems' ELSE 'cabinet' END
        AND cabinet_no IS NOT DISTINCT FROM CASE WHEN role_record.role='ems' THEN NULL::smallint ELSE 1::smallint END
        AND role=role_record.role AND local_no=1 AND valid_to IS NULL;
    IF n>1 THEN RAISE EXCEPTION 'Duplicate active role binding: %',role_record.role; END IF;
    IF n=1 THEN
      PERFORM 1 FROM device_binding WHERE id=binding_id AND device_id=role_record.device_id AND valid_from<=clock_timestamp();
      IF NOT FOUND OR role_record.existing_binding_id IS NOT NULL AND binding_id<>role_record.existing_binding_id THEN
        RAISE EXCEPTION 'Existing role binding drift: %',role_record.role;
      END IF;
    ELSE
      IF role_record.existing_binding_id IS NOT NULL THEN RAISE EXCEPTION 'Required existing role binding absent: %',role_record.role; END IF;
      INSERT INTO device_binding(binding_period_id,scope,cabinet_no,role,local_no,device_id,valid_from)
        VALUES(identity_record.period_id,'cabinet',1,role_record.role,1,role_record.device_id,clock_timestamp()) RETURNING id INTO binding_id;
    END IF;
  END LOOP;

  FOR item IN SELECT * FROM sim_definition ORDER BY namespace,source_id LOOP
    IF item.namespace='config' THEN
      INSERT INTO point_definition(catalog_version,namespace,source_id,value_type)
        VALUES('${profile.catalog.version}','config',item.source_id,'scalar')
        ON CONFLICT(catalog_version,namespace,source_id) DO NOTHING;
      PERFORM 1 FROM point_definition WHERE catalog_version='${profile.catalog.version}' AND namespace='config' AND source_id=item.source_id AND value_type='scalar';
      IF NOT FOUND THEN RAISE EXCEPTION 'Configuration type drift: %',item.source_id; END IF;
      CONTINUE;
    END IF;
    SELECT * INTO STRICT role_record FROM sim_role WHERE role=item.role;
    SELECT id INTO STRICT binding_id FROM device_binding WHERE binding_period_id=identity_record.period_id
      AND scope=item.namespace AND role=item.role AND local_no=1
      AND cabinet_no IS NOT DISTINCT FROM CASE WHEN item.namespace='ems' THEN NULL::smallint ELSE 1::smallint END
      AND valid_from<=clock_timestamp() AND valid_to IS NULL AND device_id=role_record.device_id;
    SELECT * INTO definition_record FROM point_definition WHERE catalog_version='${profile.catalog.version}' AND namespace=item.namespace AND source_id=item.source_id;
    IF FOUND AND definition_record.value_type<>item.value_type THEN RAISE EXCEPTION 'Definition wire type drift: %/%',item.namespace,item.source_id; END IF;

    -- Reuse all existing valid mappings; never duplicate or close an old binding.
    SELECT count(*) INTO n FROM point_binding pb JOIN point_definition pd ON pd.id=pb.definition_id JOIN device_binding db ON db.id=pb.device_binding_id
      WHERE db.binding_period_id=identity_record.period_id AND db.scope=item.namespace AND db.role=item.role
        AND db.cabinet_no IS NOT DISTINCT FROM CASE WHEN item.namespace='ems' THEN NULL::smallint ELSE 1::smallint END
        AND db.valid_to IS NULL AND pb.valid_to IS NULL AND pd.catalog_version='${profile.catalog.version}' AND pd.namespace=item.namespace AND pd.source_id=item.source_id;
    IF n>1 THEN RAISE EXCEPTION 'Duplicate active source mapping: %/%',item.namespace,item.source_id; END IF;
    IF n=1 THEN
      SELECT pb.measurement_point_id,pb.device_binding_id,pb.valid_from,p.kind_code,p.device_id,k.unit INTO STRICT mapping_record
        FROM point_binding pb JOIN point_definition pd ON pd.id=pb.definition_id JOIN device_binding db ON db.id=pb.device_binding_id
        JOIN measurement_point p ON p.id=pb.measurement_point_id JOIN measurement_kind k ON k.code=p.kind_code
        WHERE db.binding_period_id=identity_record.period_id AND db.scope=item.namespace AND db.role=item.role
          AND db.cabinet_no IS NOT DISTINCT FROM CASE WHEN item.namespace='ems' THEN NULL::smallint ELSE 1::smallint END
          AND db.valid_to IS NULL AND pb.valid_to IS NULL AND pd.catalog_version='${profile.catalog.version}' AND pd.namespace=item.namespace AND pd.source_id=item.source_id;
      IF mapping_record.device_binding_id<>binding_id OR mapping_record.device_id<>role_record.device_id OR mapping_record.valid_from>clock_timestamp()
         OR item.fixed_point_id IS NOT NULL AND mapping_record.measurement_point_id<>item.fixed_point_id
         OR item.unit IS NOT NULL AND mapping_record.unit<>item.unit
         OR definition_record.kind_code IS NOT NULL AND definition_record.kind_code<>mapping_record.kind_code THEN
        RAISE EXCEPTION 'Existing mapping drift: %/%',item.namespace,item.source_id;
      END IF;
      CONTINUE;
    END IF;
    IF item.fixed_point_id IS NOT NULL THEN RAISE EXCEPTION 'Required existing mapping drift: %/% -> %',item.namespace,item.source_id,item.fixed_point_id; END IF;
    generated_kind='sim_full_'||CASE WHEN item.namespace='cabinet' THEN 'c_' ELSE 'e_' END||item.source_id;
    chosen_kind=coalesce(definition_record.kind_code,generated_kind);
    IF chosen_kind=generated_kind THEN
      -- Blank unit means unverified; never infer units from a point name.
      INSERT INTO measurement_kind(code,name,unit) VALUES(chosen_kind,left('[模拟] '||item.source_name,120),coalesce(item.unit,'')) ON CONFLICT(code) DO NOTHING;
    END IF;
    SELECT * INTO STRICT kind_record FROM measurement_kind WHERE code=chosen_kind;
    IF item.unit IS NOT NULL AND kind_record.unit<>item.unit THEN RAISE EXCEPTION 'Verified unit drift: %',item.source_id; END IF;
    IF chosen_kind=generated_kind AND kind_record.unit<>coalesce(item.unit,'') THEN RAISE EXCEPTION 'Synthetic unit drift: %',item.source_id; END IF;
    INSERT INTO point_definition(catalog_version,namespace,source_id,kind_code,value_type,aggregation)
      VALUES('${profile.catalog.version}',item.namespace,item.source_id,chosen_kind,item.value_type,'last')
      ON CONFLICT(catalog_version,namespace,source_id) DO NOTHING;
    SELECT * INTO STRICT definition_record FROM point_definition WHERE catalog_version='${profile.catalog.version}' AND namespace=item.namespace AND source_id=item.source_id;
    IF definition_record.value_type<>item.value_type OR definition_record.kind_code IS NOT NULL AND definition_record.kind_code<>chosen_kind THEN RAISE EXCEPTION 'Definition semantics drift: %',item.source_id; END IF;
    generated_code='sim_full_'||CASE WHEN item.namespace='cabinet' THEN 'c_' ELSE 'e_' END||item.source_id;
    INSERT INTO measurement_point(device_id,kind_code,code) VALUES(role_record.device_id,chosen_kind,generated_code) ON CONFLICT(device_id,code) DO NOTHING;
    SELECT * INTO STRICT point_record FROM measurement_point WHERE device_id=role_record.device_id AND code=generated_code;
    IF point_record.kind_code<>chosen_kind THEN RAISE EXCEPTION 'Generated measurement point drift: %',item.source_id; END IF;
    target_point_id=point_record.id;
    IF EXISTS(SELECT 1 FROM point_binding pb JOIN device_binding db ON db.id=pb.device_binding_id WHERE pb.measurement_point_id=target_point_id AND pb.valid_to IS NULL AND db.valid_to IS NULL) THEN
      RAISE EXCEPTION 'Generated point already has another active source: %',item.source_id;
    END IF;
    INSERT INTO point_binding(device_binding_id,definition_id,measurement_point_id,valid_from)
      VALUES(binding_id,definition_record.id,target_point_id,clock_timestamp());
  END LOOP;
  SELECT count(*) INTO n FROM sim_definition s JOIN point_definition pd ON pd.namespace=s.namespace AND pd.source_id=s.source_id AND pd.catalog_version='${profile.catalog.version}'
    JOIN point_binding pb ON pb.definition_id=pd.id JOIN device_binding db ON db.id=pb.device_binding_id
    WHERE s.namespace<>'config' AND db.binding_period_id=identity_record.period_id AND db.valid_to IS NULL AND pb.valid_to IS NULL
      AND db.scope=s.namespace AND db.role=s.role AND db.cabinet_no IS NOT DISTINCT FROM CASE WHEN s.namespace='ems' THEN NULL::smallint ELSE 1::smallint END;
  IF n<>301 THEN RAISE EXCEPTION 'Expected 301 ordinary/EMS mappings; got %',n; END IF;
END $seed$;
-- Review output before commit; all new IDs are allocated by existing identity constraints.
SELECT s.namespace,s.role,count(*) AS definitions FROM sim_definition s GROUP BY s.namespace,s.role ORDER BY s.namespace,s.role;
COMMIT;
`;
}

function coverage() {
  const profile=loadProfile();
  const scenario=new FullPointScenario(DEFAULTS,profile);
  scenario.beginConnection('11111111-1111-4111-8111-111111111111',1790640000000,0);
  const kinds=['heartbeat','structure','ems','cabinet_30s','cabinet_60s','cell_voltage','cell_temperature'];
  return {synthetic:true,catalogVersion:profile.catalog.version,catalogSourceHash:profile.catalog.sourceHash,
    counts:{ordinary:295,cabinet30s:241,cabinet60s:54,ems:6,config:173,configNulls:9,reservedCellSlots:1000,voltageSlots:160,temperatureSlots:80},
    identity:DEFAULTS,roles:ROLES.map(([role,deviceId,deviceCode,existingBindingId])=>({role,deviceId,deviceCode,existingBindingId})),
    preserved:[...FIXED].map(([source,pointId])=>({source,pointId})),
    frames:kinds.map(kind=>{const m=scenario.envelope(kind,1790640000000,0);return {kind,qos:m.qos,retain:false,bytes:Buffer.byteLength(m.message)};}),
    limitations:['All data synthetic; unknown semantics remain unverified.','Only cabinet 1; no alarm placeholder registration.','Cell dimensions intentionally derived from matched synthetic fixture.','Cloud observation coverage must be verified after root applies SQL and starts the sender.']};
}

function main(argv=process.argv.slice(2)) {
  let sourceDirectory,outputDirectory=path.join(__dirname,'generated');
  for(let i=0;i<argv.length;i+=2) {
    if(argv[i]==='--source-dir') sourceDirectory=argv[i+1];
    else if(argv[i]==='--out-dir') outputDirectory=argv[i+1];
    else throw new Error('Usage: node prepare.cjs --source-dir SOURCE_DIRECTORY [--out-dir DIRECTORY]');
  }
  if (!sourceDirectory) throw new Error('--source-dir is required for original-source provenance verification');
  const sources=auditSources(path.resolve(sourceDirectory));
  fs.mkdirSync(outputDirectory,{recursive:true});
  fs.writeFileSync(path.join(outputDirectory,'bindings.sql'),buildSeedSql());
  fs.writeFileSync(path.join(outputDirectory,'coverage.json'),JSON.stringify({...coverage(),verifiedOriginalSources:sources},null,2)+'\n');
  process.stdout.write(JSON.stringify({outputDirectory,counts:coverage().counts,verifiedSourceFiles:sources.length})+'\n');
}
if(require.main===module) {try{main();}catch(error){process.stderr.write(error.message+'\n');process.exitCode=1;}}
module.exports={buildSeedSql,coverage,ROLES,FIXED,main};
